### ISSUE TITLE
Not saving any snippet in OS bigsur 11.7.10

### ISSUE THREAD

**Issue by paolodedomini** [pieces-app/support#100]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

It's not possible to save any snippet. The saving spinner keeps running...
If i try to paste the code nothing appens.
I tried any kind of snippet with no luck.

**Comment by rosie-at-pieces** [comment]
Hi @paolodedomini, at this point we only support macOS 12.0 Monterey or higher, so Pieces will not function as expected on Big Sur.
