### ISSUE TITLE
two pieces os opening option

### ISSUE THREAD

**Issue by I-am-Perspective** [pieces-app/support#102]
### Software

Pieces OS, VS Code

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Whenever you try to run vs code , it say to open pieces os application and when i do that two same options pops up ,both work exactly same imo
![Screenshot 2024-02-21 181010](https://github.com/pieces-app/support/assets/115461545/019da1f7-ce11-433c-8fc1-bf6192ced5a9)

**Comment by nathan-courtney-pieces** [comment]
Hello @I-am-Perspective 

Thanks for letting us know! I am going to have to figure out how to prevent that. We have a few processes running and it appears the Windows is picking up multiple when it should just be one. 

Clicking either of those should be fine, but I can see how it is confusing.

**Comment by nathan-courtney-pieces** [comment]
@I-am-Perspective 

If you check your list of applications on Windows, does it show that you have two Pieces OS apps installed?

**Comment by I-am-Perspective** [comment]
sorry for not sending you the screen shot my bad

**Comment by I-am-Perspective** [comment]
sorry for not sending your the screenshot my bad [image: Screenshot
2024-02-23 102802.png]

**Comment by rosie-at-pieces** [comment]
This was resolved via discord but for anyone experiencing this issue:

This usually happens because you installed it twice, from the windows store and from our website. The Pieces Suite installer will check to make sure you didn't install it from the store first but we can't do it the other way around, which is what happened here.
