### ISSUE TITLE
[Solved] Pieces OS onboarding, Jetbrains IntelliJ, PHPStorm, PyCharm

### ISSUE THREAD

**Issue by kstingel** [pieces-app/support#107]
### Software

Pieces OS, JetBrains

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When Opening a Project in Jetbrains IDE, Pieces OS Onboarding automatically opens and tells me I have no snippets saved, then invites me save a snippet

This Bug appears to be called if Jetbrains is set to auto-start Pieces OS on startup

Steps to resolve: (within JB IDE)
1. Open IDE Settings (top right menu bar or `Ctrl+Alt+S`)
2. Navigate to **`Tools > Pieces`**
3. Scroll down to **`Assistive Mechanisms`** and UNTICK `Automatically launch Pieces OS on project load`
Pieces is still available, but User Onboarding no longer opens on start - it can be opened manually if needed

Suggestion:
rather than attempting to auto-start Pieces OS server (which may already be running), 
IDEs/Browsers should first ping the server to acertain if it is running 
if the ping yields no response, it should alert the user and enquire if it should start Pieces OS or continue without Pieces Plugin active

**Comment by caleb-at-pieces** [comment]
I believe I have fixed this with the latest release of the Jetbrains plugin, please let me know if this issue still happens!
