### ISSUE TITLE
Can't connect to my personal domain

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#108]
Original ticket: 

Hello,

I can't connect to my personal domain since I've updated the app. It says my domain is already taken :

<img width="548" alt="Screenshot 2024-02-26 at 4 49 43 PM" src="https://github.com/pieces-app/support/assets/152189388/3b3a1fb6-2427-41ba-a88f-75bba0a0cba1">

Note: this issue was created automatically from an offline service ticket.

**Comment by rosie-at-pieces** [comment]
https://github.com/pieces-app/pieces_for_x/issues/502

**Comment by rosie-at-pieces** [comment]
After talking with the user, we found that their domain is actually working as expected, but isn't reflecting properly on the UI. We are currently investigating why this is happening.

**Comment by archwin010** [comment]
Hello, in my case, I just downloaded and installed the browser and extension on VSCode. But I cannot seem to connect a domain both on vscode and the app. 
![Screenshot (61)](https://github.com/pieces-app/support/assets/141458916/15933e66-af96-43f7-b927-d04063a41cd8)
![Screenshot (64)](https://github.com/pieces-app/support/assets/141458916/3a5bf616-075f-4e9b-98b0-5434ead3e2d2)
