### ISSUE TITLE
Pieces for Developers app never connects to Pieces OS

### ISSUE THREAD

**Issue by plum-stamp** [pieces-app/support#111]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

New installation in fresh VM. 

OS Name: Microsoft Windows 10 Pro N
Version: 10.0.19045 Build 19045
System Type: x64-based PC
BaseBoard Product: Virtual Machine
BaseBoard Version: Hyper-V UEFI Release v4.1
Hardware Abstraction Layer: Version = "10.0.19041.3636"

Pieces for Developers app never connects to Pieces OS as shown in image:
 
![Untitled](https://github.com/pieces-app/support/assets/64070201/f8c8b55e-b91f-433c-8ca9-11b7f1576a26)

http://[localhost:1000/.well-known/health] shows ok

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.
