### ISSUE TITLE
Download of local LLM's initializes, but never proceeds 

### ISSUE THREAD

**Issue by hercules2209** [pieces-app/support#113]
### Software

Desktop Application, Pieces OS, VS Code

### Operating System

Linux

### Your Pieces OS Version

8.0.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I was trying to download a local LLM, but any one of them that I try it is stuck on initialising. It does not start downloading the model. I have tried downloading all the available models, but it does not move further than initialising. I have seen a similar issue on GitHub for somebody using windows, but for them, it went away after updating to version 8.0.0. of pieces OS. This is their GitHub issue https://github.com/pieces-app/support/issues/84 I am already on 8.0.1 but on Linux. I am pretty sure my internet is not an issue. The rest of the app functions perfectly. It's just that I cannot download local LLMs. I have also tried to install local LLMs through VS Code, but there instead of getting stuck on initializing it gets stuck on 0% complete.

I am on Linux
pieces OS : 8.0.1
pieces for developers : 2.10.0
OS : Ubuntu 22.04 LTS
CPU: Ryzen 5800H
Ram: 16gb
GPU: RTX 3050 mobile (4gbvram)

![image](https://github.com/pieces-app/support/assets/106009563/a0d2900b-276a-4450-a0f4-100e1f8391d7)
![image](https://github.com/pieces-app/support/assets/106009563/32fc5059-a497-4b5f-9be7-e498cd56329c)

**Comment by hercules2209** [comment]
These are the logs
pieces OS
[log-03022024.txt](https://github.com/pieces-app/support/files/14465943/log-03022024.txt)
[log-03012024.txt](https://github.com/pieces-app/support/files/14465944/log-03012024.txt)

pieces PFD
[log-03022024.txt](https://github.com/pieces-app/support/files/14465948/log-03022024.txt)
[log-03012024.txt](https://github.com/pieces-app/support/files/14465949/log-03012024.txt)

**Comment by hercules2209** [comment]
This issue has since been resolved. I simply uninstalled and reinstalled both pieces Os and pfd and now it works.

**Comment by caleb-at-pieces** [comment]
> This issue has since been resolved. I simply uninstalled and reinstalled both pieces Os and pfd and now it works.

We have managed to produce this internally.

With that said rebooting Pieces OS also seems to function as a good workaround if you face this again (before we manage to fix it).

**Comment by HRA42** [comment]
I have the same issue on macOS Sonoma on a macBook Pro M3 Pro 36 GB Ram.

I tried downloading on a ipv6 only W11 VDI on MS Azure VDI, the download of a local model didn't work at all.
![CleanShot_2024-03-25_at_21 35 222x](https://github.com/pieces-app/support/assets/44985923/92af244c-bce5-4a28-9591-1e97cfbc926d)

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue was closed because it has been stale for 7 days without response from the author.

**Comment by caleb-at-pieces** [comment]
I think this issue has since been fixed by a recent update where our ML engineers significantly changed how local LLM's are handled.

**Comment by Enkouyami** [comment]
I have the same issue, but on Windows 11 with PiecesOS 11.3.4 & Pieces for Developers 4.1.1.

**Comment by yegor-pelykh** [comment]
> I am experiencing the same issue. StarCoder 2 15B says "Initializing" and it's stuck there. I click on "Stop Download" but nothing happens.

I had the same issue. Found a workaround, might be too radical, but it's the only one so far.

1) Unload all Pieces components (OS and all client applications)
2) Delete the entire folder ```C:\Users\[USERNAME]\AppData\Local\Mesh Intelligent Technologies, Inc```
3) Upon the next opening of Pieces For Developers, you will see that you need to log in to your account again. Log into your account.

This issue will no longer occur. You will be able to download on-device LLM again.
