### ISSUE TITLE
vs code extention crashes

### ISSUE THREAD

**Issue by naeemkhan9293** [pieces-app/support#115]
### Software

VS Code

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

vscode extention is not working properly it crashes every single time when i try ask copilot feature or quick fixes with pieces

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue was closed because it has been stale for 7 days without response from the author.

**Comment by caleb-at-pieces** [comment]
Hey @naeemkhan9293 is this still happening to you?
