### ISSUE TITLE
Won't let me log into my  account

### ISSUE THREAD

**Issue by THEFIG06** [pieces-app/support#116]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

every time I try and log in to my account(google or GitHub) on the developer app on windows it just brings me to my browser and a white page that won't load...Also don't know if its relevant but the extensions for both my chrome and edge say there not updated and wont let me save anything.

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.
