### ISSUE TITLE
Pieces web extension Brave browser limitations

### ISSUE THREAD

**Issue by rutvik-at-pieces** [pieces-app/support#117]
### Software

Web Extension

### Operating System

macOS

### Your Pieces OS Version

8.0.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Certain features of our web extension currently don't work on Brave. For e.g. Saving or sharing a snippet from embed buttons shown around snippets or from context menu actions on a site.

This is due to how Brave operates and its security policies and settings. Brave blocks any of the outgoing/incoming connections from a untrusted network. Unfortunately, web extension needs to communicate with Pieces OS over a localhost network which runs over `http` protocol which is seen as unsafe by Brave. Due to this limitation, certain features of web extension as mentioned above don't work when run through the running site context. 

Though this features are available and run perfectly fine when using them through the extension side panel or popup. We're still investigation how we can get around this issue but haven't yet been able to found a proper solution to this problem. 

Users can get around this issue by changing Brave security setting but I doubt anyone using Brave would wanna do that. 

<img width="1064" alt="Screenshot 2024-03-06 at 1 38 12 PM" src="https://github.com/pieces-app/support/assets/144297703/c1a716f8-0714-4fc5-be70-9410b2ad4597">

Untill we find a proper solution for this, if you wanna experience full capabilities of our web extension, would recommend using other browsers like Chrome, Edge, Firefox or Opera.

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by aqdasak** [comment]
Same problem exists in Librewolf browser, but the side panel doesn't work either.

**Comment by rutvik-pieces** [comment]
@aqdasak We don't officially support Librewolf browser yet. As a result some functionality may be broken there if it has its own independent extension api different from the ones common in chromium based browsers. 

Atm we don't have any plans to officially support `Librewolf` but might be in the future. You can still use the web extension in other browsers like Chrome, Edge or Firefox which are few of the officially supported browsers.

**Comment by rutvik-at-pieces** [comment]
Web extension should be now working properly in the latest v4.0.0 of the extension in Brave. Closing as resolved.
