### ISSUE TITLE
Windows - Unable to Connect to Pieces OS

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#118]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

We have found that users who have some sort of proxy set up on all their machines may experience a connection failure with Pieces. We have only seen this on Windows so far but it could also be the case for Mac or Linux.

This happens when Pieces tries to look up localhost:1000 as part of its processes, which is replaced by that proxy if the user has one set up, thus causing Pieces to throw a connection error. 

What the user will see:
<img width="792" alt="pieces_for_x_TYwzf8TJJi" src="https://github.com/pieces-app/support/assets/152189388/8cfd9ba4-9416-480b-b413-9347def421da">

The proxy set up:
<img width="440" alt="SystemPropertiesAdvanced_xi19AWA3BM" src="https://github.com/pieces-app/support/assets/152189388/d631f52a-8cad-4a51-b552-3be103fb08b7">

The error:
<img width="883" alt="Notepad_aT5QkbBVHj" src="https://github.com/pieces-app/support/assets/152189388/199cf2a9-1386-48c3-8b37-9619a2c8923a">

You can check your logs to see if this is the error you are receiving, they can be found at:
C:\Users\<user_name>\Documents\com.pieces.pfd\production\logs
C:\Users\<user_name>\OneDrive\Documents\com.pieces.pfd\production\logs (if using onedrive)

We are working on a solution for this now, but in the meantime if you can remove that proxy it will allow Pieces to work as expected.

**Comment by rosie-at-pieces** [comment]
We have found a solution for this and expect it to release next week with PiecesOS v8.1.0!

**Comment by mark-at-pieces** [comment]
I believe this should be resolved going to close this issue
