### ISSUE TITLE
Error in the pieces os

### ISSUE THREAD

**Issue by shamavachar** [pieces-app/support#120]
### Software

Pieces OS, VS Code, Web Extension

### Operating System

Windows

### Your Pieces OS Version

8.0.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

when i give any prompt it says sorry something wrong in this prompt for every prompt

**Comment by rosie-at-pieces** [comment]
hi @shamavachar which LLM are you using when you experience this issue?

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue was closed because it has been stale for 7 days without response from the author.
