### ISSUE TITLE
Pieces app doesn't return response after prompting

### ISSUE THREAD

**Issue by nbriggsrsi** [pieces-app/support#122]
### Software

Pieces OS, VS Code

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Using various models, I will sometimes encounter an issue where after entering a prompt, Pieces returns nothing. It appears to read the prompt, shows the relevant files in a list below the prompt, and a message that says "Almost there" appears. But then both the relevant files and "Almost there" message disappears, and then it just seems to "give up."

I've had this happen with other models, but in this case, I was trying the Bison model. Also I've noticed when I get this message, I keep getting this message. Then all of a sudden, a day later in one case, it starts working again.

**Comment by caleb-at-pieces** [comment]
Couple things that will help us get to the bottom of this issue:

1. does restarting Pieces OS and / or VS Code resolve this issue?
2. when this issue occurs, do you also see the same issue in other integrations like the Desktop App?
3. Does this happen more often for specific models?
4. Were you doing anything else before this happened? Some exact steps to reproduce would be great!

**Comment by nbriggsrsi** [comment]
Let me try your suggestions, and I'll get back to you. I can tell you now that restarting VS Code does not solve the issue, and it seems to be happening mainly with the cloud models, which is strange. I have a GPT4 API key from my subscription and tried using that, and even that gives me the same result.

Changing to Mistral 7B CPU on-device seems to solve the issue though and it gave me some decent results too, which I'm happy about.

I'll keep playing with this and get you some exact steps to see if you can reproduce the error. 

My hope also was that, like GPT4, it would have the ability to reach out online to read documentation to add to its context. Is there any way to achieve that? Just curious.

**Comment by caleb-at-pieces** [comment]
> Let me try your suggestions, and I'll get back to you. I can tell you now that restarting VS Code does not solve the issue, and it seems to be happening mainly with the cloud models, which is strange. I have a GPT4 API key from my subscription and tried using that, and even that gives me the same result.

Excellent, thank you for the info. Let us know if you have some more details later.

> My hope also was that, like GPT4, it would have the ability to reach out online to read documentation to add to its context. Is there any way to achieve that? Just curious.

Our Copilot does not currently have the ability to *search* the web however you are able to use websites as context in the VS Code extension as of the 1.13.0 release (about 8 days ago)

**Comment by caleb-at-pieces** [comment]
@nbriggsrsi @sunarkadeep 

I have just had this happen to me within VS Code and I checked my developer tools console *(Help > Toggle Developer Tools)*and see this error message:

<img width="404" alt="image" src="https://github.com/pieces-app/support/assets/133268200/cbfea321-3a1b-4f87-a0b1-9c1ca9065ce4">

Can someone confirm this is the same error message they see in their logs?

**Comment by sunarkadeep** [comment]
@caleb-at-pieces how can I reach this? after _Help > Toggle Developer Tools_ .....because then a window appears and there's too many things to look at....

**Comment by caleb-at-pieces** [comment]
> @caleb-at-pieces how can I reach this? after _Help > Toggle Developer Tools_ .....because then a window appears and there's too many things to look at....

You can do so like this too:

1. `ctrl + shift + p` for linux / windows or `command + shift + p` for macos to open command palette
2. search: 'Toggle Developer Tools'
3. select the first option to open developer tools.

**Comment by sunarkadeep** [comment]
okay so I did that but nothing sort of log as you posted appeared on mine.... what I got is just 
![image](https://github.com/pieces-app/support/assets/119619239/cd00c7e0-bbde-4076-ab23-52b4d6bee962)

**Comment by caleb-at-pieces** [comment]
> okay so I did that but nothing sort of log as you posted appeared on mine.... what I got is just ![image](https://private-user-images.githubusercontent.com/119619239/312594981-cd00c7e0-bbde-4076-ab23-52b4d6bee962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTgyNTMsIm5iZiI6MTcxMDM1Nzk1MywicGF0aCI6Ii8xMTk2MTkyMzkvMzEyNTk0OTgxLWNkMDBjN2UwLWJiZGUtNDA3Ni1hYjIzLTUyYjRkNmJlZTk2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxOTI1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzFlNmY5NDEyMTg3MGViMjg1MmQ2Mzg0MzNiMzNhNTJlMjUzMGViMjNlY2Y3ZDQ5YTMyZjk4ODMwOTUwYjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6czyDqc5EGLuJe-tc4X-ilqmb-SJ2pl4WKwq_QWfzn8)

Great, if you happen to encounter the same issue again please check and put the output here in this thread!

**Comment by tsavo-at-pieces** [comment]
@caleb-at-pieces did we get a fix in for this?

**Comment by sunarkadeep** [comment]
@caleb-at-pieces 
so a quick update, the issue is still persistent....like the very first reply from the copilot in a new chat just appears and disappears...like really quickly....thus taking me back to the pieces copilot home page in the side panel...then the only way to access the conversation again is to either close and reopen vscode or close copilot from the side panel and reopen it.....and also in vscode console, there is no such error or issue statements...

and the problem with refreshing in pieces desktop app is not there anymore...so just the vscode one is there

**Comment by caleb-at-pieces** [comment]
@sunarkadeep We should be releasing a change in the next version of the VS Code extension that will fix this. So hang tight for a bit and this problem should be resolved soon.

**Comment by sunarkadeep** [comment]
@caleb-at-pieces 
okay so the response delay of copilot within vscode now seems to have been solved. I can finally see immediate response and it works just the way it should 👍
