### ISSUE TITLE
the latest release on windows is detected by Kaspersky as a Trojan

### ISSUE THREAD

**Issue by SmoothDenis** [pieces-app/support#128]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

latest

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

https://www.virustotal.com/gui/file/baf9c933dcc9edc8d24a46ab56cfed734fe48c612c6d3f36ef15e7038118db5a/detection

maybe because of the file tokenizer.dll or something like that

**Comment by rosie-at-pieces** [comment]
Hi @SmoothDenis thanks for letting us know - unfortunately we can't do anything about this, you would have to white-list PiecesOS and the Pieces Desktop App on the antivirus software.
