### ISSUE TITLE
Trojan Detected By Kaspersky while trying to remove app

### ISSUE THREAD

**Issue by suygetsu1256** [pieces-app/support#130]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

Last version

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I did not have an api key so i decided to delete pieces but then i got trojan detected message by kaspersky

Event: Malicious object detected
User: NT AUTHORITY\SYSTEM
User type: System user
Application name: svchost.exe
Application path: C:\Windows\System32
Component: File Antivirus
Result description: Detected
Type: Trojan horse
Name: Trojan-Dropper.Win64.Agent.akt
Accuracy: High
Threat level: High
Object type: File
Object name: tokenizers.dll
Object path: C:\Program Files\WindowsApps\com.MeshIntelligentTechnologi.PiecesOS_8.0.0.0_x64__84gz00a5z79wr
MD5 of an object: 5619D7C7C45B8542BB3B05AB712BF69B
Reason: Databases
Database version date: Today, 18.03.2024 09:54:00

**Comment by suygetsu1256** [comment]
![image](https://github.com/pieces-app/support/assets/163304292/9bb5a78d-3e6c-48f6-8553-5d19a65220c4)

**Comment by rosie-at-pieces** [comment]
hi @suygetsu1256 thanks for reaching out! just so you know, you do not need your own API key for Pieces to work, you can just use one of the models we offer. we offer several from OpenAI, Google, Meta, and more. 

that tokenizer.dll is an expected part of Pieces so if you want Pieces to continue to run properly you will have to white-list it with kaspersky. 

if you want to delete Pieces completely you should be able to just quit Pieces and PiecesOS, then right-click on the Pieces apps within your "Apps" on Windows, and remove your local databases by deleting the "com.pieces.os" and "com.pieces.pfd" folders within your Documents folder.

**Comment by suygetsu1256** [comment]
> hi @suygetsu1256 thanks for reaching out! just so you know, you do not need your own API key for Pieces to work, you can just use one of the models we offer. we offer several from OpenAI, Google, Meta, and more.
> 
> that tokenizer.dll is an expected part of Pieces so if you want Pieces to continue to run properly you will have to white-list it with kaspersky.
> 
> if you want to delete Pieces completely you should be able to just quit Pieces and PiecesOS, then right-click on the Pieces apps within your "Apps" on Windows, and remove your local databases by deleting the "com.pieces.os" and "com.pieces.pfd" folders within your Documents folder.

sure but whats the reason of the detection its weird it detects as virus a signed file

**Comment by rosie-at-pieces** [comment]
@suygetsu1256 we're investigating that right now!

very sorry for the inconvenience.

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue was closed because it has been stale for 7 days without response from the author.
