### ISSUE TITLE
Context not working as expected when adding a directory

### ISSUE THREAD

**Issue by nootn** [pieces-app/support#132]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I load up a new chat and set the context to a folder that has some sample code in it:
![image](https://github.com/pieces-app/support/assets/1258499/54cf872e-38fd-48bb-88d2-13e0c710a0ca)

If I switch to the local Mistral 7B GPU model, it's definitely using the model, I can see my GPU spike and it does answer, but it doesn't seem to be able to get the context:
![image](https://github.com/pieces-app/support/assets/1258499/cdee2a11-529c-4fc0-ad35-50d3b69715b6)

If I switch to the model to GPT4 Turbo (cloud hosted), and get a similar result - so I don't think it's the model, the chat seems to not be picking up the context from the directory:
![image](https://github.com/pieces-app/support/assets/1258499/1226fc3f-1850-494c-b734-c59190b01a07)

Here is a copy of the folder, there is definitely a readme and a json file in the root level:
![image](https://github.com/pieces-app/support/assets/1258499/8f4c08eb-9db9-4b90-a690-6633563ec004)

**Comment by sam-at-pieces** [comment]
Thanks for the detailed, clear issue @nootn. You are correct, this is not related to the model choice, it was a deeper bug in the way we parse the directory which should be fixed in our next release.

**Comment by sam-at-pieces** [comment]
@nootn we just released an update (OS server 8.1.0), I would love to hear what you experience is like now
