### ISSUE TITLE
Context is not working at desktop app for Linux

### ISSUE THREAD

**Issue by carrycooldude** [pieces-app/support#133]
### Software

Desktop Application, Pieces OS

### Operating System

Linux

### Your Pieces OS Version

1.13

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

After adding prompt , it's not showing the result and I tried multiple times.

**Comment by nathan-courtney-pieces** [comment]
@carrycooldude 

Are you having issues with Context, or are you not able to use the copilot at all? If you are able to send over screenshots that would help us out. 

You can also run this command within your terminal to generate a log output. 

$ pieces-os --debug --verbose

If you could run that and try to interact with the software to produce the error, it will likely get logged and you can post that here for the team to take a look.

**Comment by carrycooldude** [comment]
Now it's working , I don't know how but thanks for sharing your inputs.
