### ISSUE TITLE
Windows Pieces App not running (keep restarting)

### ISSUE THREAD

**Issue by trungkoiiNe** [pieces-app/support#134]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi. Recently my Destop App meets a problem that it can't open ( it keeps restarting in the background). The Pieces OS showing Connecting Pieces App
![image](https://github.com/pieces-app/support/assets/134728377/2899af7b-45e1-4217-a9ad-204e6488a45e)

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue was closed because it has been stale for 7 days without response from the author.
