### ISSUE TITLE
Not able to make pieces read the whole code base and explain the project

### ISSUE THREAD

**Issue by hcapp01** [pieces-app/support#143]
### Software

VS Code

### Operating System

macOS

### Your Pieces OS Version

N/A

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

in chat window
@workspace
explain the project
------
I'm sorry, but I don't have access to the specific project you're referring to. Could you please provide more information or context about the project you would like me to explain?

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.
