### ISSUE TITLE
Very slow AI response on W-11 but fine on MAC OS.

### ISSUE THREAD

**Issue by Charlatan2k** [pieces-app/support#144]
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

So when using Pieces desktop for asking questions no matter the LLM it takes like sometimes a whole minute or more to respond to simple questions like "What is a React Hook". And I decided to test it on my M1 PRO Mac and it worked fine with the same question being answered within seconds and in even more detail.

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.
