### ISSUE TITLE
not able to connect my github and google account on Pieces app

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#15]
Note: this ticket was created due to several users reaching out about this issue.

**Comment by rosie-at-pieces** [comment]
This is an issue we are seeing across all platforms, and it happens when a user has signed in first with Github and then attempts to connect additional accounts like Github or email-pass. 

At the moment, we need to manually fix your account to resolve this, so please reach out to us using our [support form](https://getpieces.typeform.com/to/mCjBSIjF#page=docs-sidebar) and we will take care of it for you. 

We are working on a full fix for this and it should be out in the next couple of releases. We will update this ticket when it has been released!

**Comment by rosie-at-pieces** [comment]
https://github.com/pieces-app/os_server/issues/59

**Comment by jimbobbennett** [comment]
Closing as #260 is a dup
