### ISSUE TITLE
Latex response in the chat is not compiled

### ISSUE THREAD

**Issue by Sorcerer14** [pieces-app/support#152]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

8.1.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

As you can see, the latex in the response is not getting compiled
![Screenshot 2024-04-09 234148](https://github.com/pieces-app/support/assets/83954824/754a02be-1835-4f11-8976-43139d7dfe4d)

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by jimbobbennett** [comment]
Thank you for your feedback - we are tracking this internally and will prioritize. I'll close this issue in the meantime.
