### ISSUE TITLE
When pasting Ladder Logic into the pieces cp pilot app

### ISSUE THREAD

**Issue by GreatSmattering** [pieces-app/support#154]
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

most recent

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When I selected and copied a section of ladder rungs from a Directsoft 6 program into the co pilot, it simply responded that it indeed can interpret ladder logic. But nothing about the code, or if it was even recieved by the ai at all.

Thank you from the industrial controls world!

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by GreatSmattering** [comment]
No worries my friend!

I was trying to copy and paste a section of ladder logic and all that
pasted was the program file name and n the pieces co pilot.

Best regards
Andrew

**Comment by jimbobbennett** [comment]
@GreatSmattering - sorry, as much as I dabble in IoT industrial controls is outside my wheelhouse. I mean, I've heard of OPC UA but that's it...


Can you share the full text of your prompt with the ladder logic?
