### ISSUE TITLE
Copilot Chats incorrectly labels C# code as JavaScript

### ISSUE THREAD

**Issue by codename-irvin** [pieces-app/support#159]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

8.1.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Desktop application version is 2.11.0

**Observed behavior**: In the image below, you can see that ChatGPT was asked to generate C# code, which it did. However, Pieces incorrectly labels the code snippet as JavaScript. 

**Expected behavior**: The snippet of code should correctly be labeled as C#.

I was able to reproduce the same issue on the Windows desktop app as well. Same versions.

<img width="857" alt="Screenshot 2024-04-12 at 10 05 44 AM" src="https://github.com/pieces-app/support/assets/100172500/95d9ac33-5ba8-471e-8894-0446d7870cf6">

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment]
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mack-at-pieces** [comment]
Hi @codename-irvin - Thanks for sharing here. Do you mind sharing the prompt you used and the LLM runtime you were using so that I can try and reproduce this? Thanks!

**Comment by codename-irvin** [comment]
@mack-at-pieces the prompt that I used was "Iterate over a list in C#". I just tested with GPT 3.5, GPT 4, PaLM 2, and Gemini. Interestingly, I was able to reproduce for all but Gemini. With Gemini, it correctly labeled the snippet as C#. The others all labeled the snippet as JavaScript.

**Comment by jimbobbennett** [comment]
Cannot reproduce with Pieces 3.2.2.
