### ISSUE TITLE
when i generate a shareable link in Pieces for snippets and share it with others the link does not open

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#16]
Note: this ticket was created because several users reached out to us about this issue.

![977114e85b12-pieces_error](https://github.com/pieces-app/support/assets/152189388/983aa85c-997a-4c3f-a4b7-959777f4b3e4)

**Comment by rosie-at-pieces** [comment]
This can sometimes be caused by a resource limitation issue, so we need to check your account to see if that is the case. Please reach out to us directly using the [support form](https://getpieces.typeform.com/to/mCjBSIjF#page=docs-sidebar) so we can take a look. 

That said, last week we found a minor issue causing shareable links/gists to occasionally fail. One workaround we have right now is if you create a brand new snippet (via a manual copy/paste or via the edit menu and duplicate) then attempt to generate that as a shareable link you can sometimes get a success. 

We are working on a solution to ensure Shareable links have a 100% success rate. This fix will be going out in the release of PiecesOS on Thursday Jan 11th with the version number 7.2.0.

**Comment by rosie-at-pieces** [comment]
https://github.com/pieces-app/os_server/issues/468

**Comment by mark-at-pieces** [comment]
Update: was a strange issue related to shareable links failing occasionally when there are a lot of tags/websites, very inconsistent. That being said this issue will be fixed in 7.2.0.

Also, there can be issues related to resourcing problems so I'm going to keep this ticket open.

For anyone in the future, feel free to @me and I can take a look into any cloud/gist/shareable links issues. :) 

Happy Coding!

**Comment by ramarivera** [comment]
Hey @mark-at-pieces ! 
I'm having issues with generating shareable links:
- The one time it worked, it was corrupted :(
- It didn't use my cloud domain
- Now it just throws an error

+ Cannot connect to my github account yet
![Screenshot 2024-02-25 at 03 50 36](https://github.com/pieces-app/support/assets/7547875/81403486-8943-4169-9d10-1668413a0333)

**Comment by mark-at-pieces** [comment]
> Hey @mark-at-pieces ! I'm having issues with generating shareable links:
> 
> * The one time it worked, it was corrupted :(
> * It didn't use my cloud domain
> * Now it just throws an error
> 
> * Cannot connect to my github account yet
>   ![Screenshot 2024-02-25 at 03 50 36](https://private-user-images.githubusercontent.com/7547875/307562965-81403486-8943-4169-9d10-1668413a0333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTcxNDYsIm5iZiI6MTcwODk1Njg0NiwicGF0aCI6Ii83NTQ3ODc1LzMwNzU2Mjk2NS04MTQwMzQ4Ni04OTQzLTQxNjktOWQxMC0xNjY4NDEzYTAzMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTQxNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ3MGE1NGFlMWZmYTRmZjRhODYzNTE4NzlmYjU3MzdjNDYwZDQ1ZDcyY2FlOGZiMmE4M2VkMzIxNDliNjljNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WpATDS7a0rNxR0uVWUjeWkK8EgItfxrAUSag96sBkEY)

sorry to hear you having issues with generating shareable links would you mind sending me your email that you use to signinto pieces, feel free to just email me at mark@pieces.app

**Comment by jimbobbennett** [comment]
Known issue and on the internal roadmap. Closing to reduce noise
