### ISSUE TITLE
activate WPE not possible

### ISSUE THREAD

**Issue by HRA42** [pieces-app/support#176]
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

9.0.0

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I try to start the WPE feature:
![image](https://github.com/pieces-app/support/assets/44985923/37c8867e-179f-454c-9cb3-6f714f251c8d)
After that, pieces os crashes and pieces desktop shows the not connected message. Restart pieces os does work, but WPE isn't enabled after that.

[log-04182024.txt](https://github.com/pieces-app/support/files/15022438/log-04182024.txt)
This is the latest log file from today from com.pieces.os\production\Support\logs

[log-04182024.txt](https://github.com/pieces-app/support/files/15022449/log-04182024.txt)
And the Logs from com.pieces.pfd\production\logs

**Comment by rosie-at-pieces** [comment]
We found this issue, fix in progress! ETA likely tomorrow!

**Comment by mark-at-pieces** [comment]
will be live w/ 9.0.1 either this evening or tomorrow afternoon

https://github.com/pieces-app/os_server/issues/709
