### ISSUE TITLE
Snippet Discovery does not produce results for Drupal or Symfony-based (PHP) projects

### ISSUE THREAD

**Issue by neuronick** [pieces-app/support#189]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

9.0.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When trying to use Snippet Discovery on a Drupal project or Symfony-based projects no useful snippets are discovered. Either "nothing found" message is shown or the system finds some useless CSS snippets.

When pointing Snippet Discovery to a node.js project/files or python project/files everything works as expected.

**Comment by sam-at-pieces** [comment]
Thanks for getting in touch @neuronick. Currently our snippet discovery uses Tree Sitter to parse the AST of any code files found. The PHP grammar used with tree sitter is still very buggy and not stable enough to include in our offering. It is unlikely we will be able to support snippet discovery in PHP until the PHP tree sitter grammar stabilizes. 

However, you will be able to explore those folders using our copilot by setting them as context and find useful snippets that way as this does support PHP!

**Comment by sam-at-pieces** [comment]
@neuronick that's an excellent point, we'll get that added asap. Thanks again for the feedback, closing this for now until we find a workaround for PHP
