### ISSUE TITLE
Codebase repository folder not accounted for

### ISSUE THREAD

**Issue by luchfilip** [pieces-app/support#192]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

2.12.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Steps

1. new chat
2. add folder
3. Set context section shows one folder 
4. Local Mistral 7B is selected as the model(downloaded successfully before)
5. ask chat "Tell me about the MVPDAuthActivity from [folder name] project"
6. model says it doesn't have access. As if I didn't add any context
The codebase is a fully working codebase that has that activity. 
![Screenshot 2024-05-01 at 12 30 50 PM](https://github.com/pieces-app/support/assets/5247619/d80d44d7-ba38-4724-8987-37dd77d90a06)
![Screenshot 2024-05-01 at 12 34 23 PM](https://github.com/pieces-app/support/assets/5247619/c65d3040-d28d-4737-a3ad-2a04a4132629)

**Comment by sam-at-pieces** [comment]
Thanks for raising this @luchfilip, I'd love to know a couple of things to help triage this:
- what languages were in the selected contet?x
- how large was the selected context folder?
- approx how long did you wait from adding the context to asking about it?
Thanks for your help!
