### ISSUE TITLE
Use the same conversation each time I use "Pieces:Explain" for a file

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#197]
### Software

VS Code

### Operating System

macOS

### Your Pieces OS Version

9.0.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

A user requested this because they mainly use the VSCode extension as a copilot for helping debugging and they would like to stop the extension from creating new conversations each time they use "Pieces:Explain." It would be better to always use the same conversation since they are working in a single repo/codebase.

**Comment by caleb-at-pieces** [comment]
just got a new feature in for this the default behavior should soon be to use the same conversation for code lens actions within the same file

**Comment by caleb-at-pieces** [comment]
Just made this the default behavior.
