### ISSUE TITLE
Pieces Extension for Microsoft edge is not working

### ISSUE THREAD

**Issue by tuhin47** [pieces-app/support#206]
### Software

Web Extension

### Operating System

Linux

### Your Pieces OS Version

2.9.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I faced two problems with the browser extension.
1. Ask Co-pilot and the setting button is not working.
![ksnip_20240512-083908](https://github.com/pieces-app/support/assets/15657474/f2ae8caf-4cc7-4a7c-bdde-b544b573bb44)
2. Side panel view not available. Probably a problem with [menifest.json](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/sidebar)

**Comment by tuhin47** [comment]
CUrrently It is resolved on **Microsoft Edge 125.0.2535.51**

**Comment by mack-at-pieces** [comment]
Thanks so much @tuhin47 !
