### ISSUE TITLE
Pieces OS automatically closes on using a Local LLM for chat

### ISSUE THREAD

**Issue by lakshits11** [pieces-app/support#208]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

Latest one as of today

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

So i installed mistral 7b gpu . I have rtx 4050 6gb on my machine. When i ask a question, pieces os automatically closes. Please help.

**Comment by tsavo-at-pieces** [comment]
@brian-pieces I think this is related to #235 

@lakshits11 we're on it. Release for big improvements to Local LLMs coming in about 7 days 🤝

**Comment by jimbobbennett** [comment]
Closing as a duplicate of #235. Please follow that bug for more details.
