### ISSUE TITLE
anchors and file name and line numbers are not populated automatically

### ISSUE THREAD

**Issue by yehudamakarov** [pieces-app/support#211]
### Software

Desktop Application, Pieces OS, JetBrains

### Operating System

macOS

### Your Pieces OS Version

9.0.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

as per https://docs.pieces.app/features/auto-enrichment#saving-a-snippets-origin-information

> Saving a snippet’s original context is helpful for organization and future use. Pieces automatically extracts and saves the following contextual information:
>
> Project Name
Source File
Line Numbers
Collaborators
Application Source (Chrome, Edge, VS Code, etc.)
Solution Publishers

**source file and line numbers are not populating**
- either from the jetbrains extension
- or just a regular copy

**Comment by mack-at-pieces** [comment]
Hi @yehudamakarov - Thank you for bringing this to our attention. The team has a patch queued up for the JetBrains plugin that should resolve this. We are planning to have that released early next week 👍🏼

**Comment by yehudamakarov** [comment]
I will reinstall when that is in the works! Looking forward, thanks for the hard work

**Comment by caleb-at-pieces** [comment]
This should be fixed with one of the later releases of the Jetbrains Plugin.
