### ISSUE TITLE
Broken Markdown URLs when clicking in Obsidian

### ISSUE THREAD

**Issue by LucaMarconato** [pieces-app/support#215]
### Software

Obsidian

### Operating System

macOS

### Your Pieces OS Version

9.0.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When I chat with a bot via the Obsidian interface and the answer includes a URL, if I click the URL a broken link is opened.

For instance see this:
<img width="785" alt="image" src="https://github.com/pieces-app/support/assets/2664412/ee741adb-9a45-4364-917e-938296f9121c">

If I click on the link, the following URL opens in the browser: `https://z/`.

Please note that the markdown answer is correct:

<img width="784" alt="image" src="https://github.com/pieces-app/support/assets/2664412/1cf3f3e9-37ed-43be-b18d-31cd6ce44a53">

therefore I think the bug is related to clicking/opening the link.

**Comment by caleb-at-pieces** [comment]
Hello! @LucaMarconato 

Thank you for pointing this out, I have managed to find a fix for this and it will be in the next update of the Obsidian plugin!
