### ISSUE TITLE
cant install pieces on my desktop

### ISSUE THREAD

**Issue by patelishwar22** [pieces-app/support#216]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

latest

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

App installation failed with error message: Appinstaller operation failed with error code 0x80070422. Detail: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (0x80070422) - from many days when i install this app this error comes and i find every possible solution but didnt work and so now i am here

**Comment by nathan-courtney-pieces** [comment]
Hello @ishupatel07 

Sorry to hear that you are having issues! Appears that App Installer is having problems. 

Can you try opeing up the Microsoft Store and update your App Installer application?

**Comment by ishupatel07** [comment]
ya sure ! okay i am doing that
