### ISSUE TITLE
Can't save code snipped to Github gists

### ISSUE THREAD

**Issue by keypuncherlabs** [pieces-app/support#218]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

Version 2.12.2 (2.12.2)

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I'm getting an error when trying to save a code snippet to Github gist using the built in publish mechanism.

<img width="1637" alt="Screenshot 2024-05-21 at 12 51 50 PM" src="https://github.com/pieces-app/support/assets/266783/3b02fa08-ce8e-4eb1-ac1b-aa7e5b888ee3">

**Comment by mack-at-pieces** [comment]
Hey @keypuncherlabs Thanks for bringing this to our attention. The team is actively investigating this. We'll update this issue as we have more information. Hang tight!

**Comment by mark-at-pieces** [comment]
@keypuncherlabs would you mind providing me w/ your email, so that I can take a deeper look. If you would prefer, please feel free to launch me an email at mark@pieces.app
