### ISSUE TITLE
Pieces OS stability

### ISSUE THREAD

**Issue by bardo84** [pieces-app/support#219]
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

2.12.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I often have to restart Pieces OS and desktop.
No further error message.

**Comment by mark-at-pieces** [comment]
Hey @bardo84 Sorry your getting this issue, this is definitely not intended. Would love to learn more, here is a link to my calendar. Would be super helpful for a video or if we could chat in realtime so I can help debug what is going on.

https://calendar.app.google/uk7aKZc13EQb6Y8Z7
