### ISSUE TITLE
GPT keeps loading the answer

### ISSUE THREAD

**Issue by ivanperazzo** [pieces-app/support#222]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

Pieces OS 9.0.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Whenever I select Chat GPT as Copilot Runtime I can't get any type of answer, if I select Gemini, everything works ok. Im using my API key from Chat GPT Plus.

[log-05232024.txt](https://github.com/pieces-app/support/files/15417354/log-05232024.txt)
![image](https://github.com/pieces-app/support/assets/50222338/71913b19-30fb-4b9a-b5e7-a91282886611)

**Comment by mack-at-pieces** [comment]
Hi @ivanperazzo Thanks for reaching out. So sorry you're running into issues. Can you please confirm that your API Key from ChatGPT Plus is still valid and has not expired? Thanks!
