### ISSUE TITLE
VS Code Extension won't save snippets

### ISSUE THREAD

**Issue by Psymon07** [pieces-app/support#229]
### Software

VS Code

### Operating System

Windows

### Your Pieces OS Version

9.0.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I feel there's something I'm missing, but when using the **Pieces Extension** in **VS Code** I can't save any snippets. Nothing happens.
I have Pieces installed on three devices, across Windows 10 and 11. All of them have up to date versions and all run Pieces OS fine. I have an account, which signs in fine as well. The Pieces Desktop App loads and shows me my saved snippets, letting me save and edit new snippets.
In **VS Code** I have the **Pieces extension** installed on all three machines. I highlight some code, right click and hit Save to Pieces and nothing happens. No error, no notification, nothing.
I've searched for possible settings that I've changed, even uninstalled the extension and installed it again. Any help would be greatly appreciated

I expected that when I hit Save to Pieces the code snippet would appear in the list of saved materials. The list updates in real time if I copy the code and paste it into the Pieces Desktop app.

https://github.com/pieces-app/support/assets/170961170/aaec87a7-3862-4447-b5d2-6536f524bc8c

**Comment by Psymon07** [comment]
Hi Mack,
Thanks for getting back to me. I'm not running VS Code remotely, each machine runs it locally and I use Git to centralise my projects. I occasionally use a remote extension in VS Code to view some Repos, if I want to make a quick code check without having to clone the whole Repos. I hope that Pieces will make this process easier, as it can store all my code snippets.

I'm running version v1.16.0 of the VS Code Extension

The developer console does show some errors when trying to save a snippet through VS Code
![Errors](https://github.com/pieces-app/support/assets/170961170/a05c2898-de9e-4633-ade3-8816362dc6e9)

**Comment by caleb-at-pieces** [comment]
Hey @Psymon07 

Thanks a lot for showing me these logs, using this I've been able to narrow down what is going on here. A fix should be out for this in the next release of the VS Code extension!
