### ISSUE TITLE
Blog Syntax Highlighting

### ISSUE THREAD

**Issue by tsavo-at-pieces** [pieces-app/support#234]
### Software

Blog (code.pieces.app/blog)

### Operating System / Platform

Web

### Your Pieces OS Version

N/A

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Looks like there are some syntax highlighting issues on the Pieces Blog. 

Also reported by @jimbobbennett 

https://code.pieces.app/blog/build-a-copilot-with-phi-2-using-pieces-client#create-amp-enable-phi-2-download-buttons

![image](https://github.com/pieces-app/support/assets/102485237/51c00a0f-9f51-4ae6-adf6-7a0f8f087d92)

**Comment by georgia-at-pieces** [comment]
<img width="838" alt="Screenshot 2024-05-31 at 10 24 07 AM" src="https://github.com/pieces-app/support/assets/100875449/7516182b-1c07-4c66-8ea8-1dadd34cd90c">
 This is what that snippet looks like from Storychief— I'm not sure how to fix it & would love some help! @mason-at-pieces

**Comment by mason-at-pieces** [comment]
@tsavo-at-pieces @georgia-at-pieces Fixed: https://code.pieces.app/blog/build-a-copilot-with-phi-2-using-pieces-client#create-amp-enable-phi-2-download-buttons

It just had weird spaces in the actual content
