### ISSUE TITLE
connecting my Pieces account to VS Code isn't working

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#24]
### Software

VS Code

### Operating System

macOS

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

1. click the connect button
2. it spins forever

**Comment by rosie-at-pieces** [comment]
https://github.com/pieces-app/plugin_vscode/issues/254

**Comment by caleb-at-pieces** [comment]
Hi guys, just managed to find a fix for this, it should be out in the VS Code extension 1.11.0 release.
