### ISSUE TITLE
Word Break Issue in Text Input Field - Obsidian Extension

### ISSUE THREAD

**Issue by elliezub** [pieces-app/support#245]
### Software

Obsidian

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.5

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When entering text into the input field, the text breaks in the middle of words instead of wrapping to the next line properly. This causes the text to be difficult to read and disrupts the user experience.
![Screenshot 2024-06-05 130053](https://github.com/pieces-app/support/assets/112726692/c6dc8016-0055-481a-8f52-48c0005fac1e)

**Comment by caleb-at-pieces** [comment]
Hey @elliezub !

Thank you for pointing this out, I should be able to get a fix out for this in the next release of the Obsidian plugin. I expect that it will be released around Monday next week.

**Comment by elliezub** [comment]
Awesome! Thanks @caleb-at-pieces 😄
