### ISSUE TITLE
Gibberish & irrelevant Suggestions with small, moderately advanced C# Codebase as context

### ISSUE THREAD

**Issue by thygrrr** [pieces-app/support#249]
### Software

JetBrains

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.5

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I have a library of around 7500 LoC (much of it comments/documentation) of modern C# that I set as context. The project is 100% C#.

### Context for Reproduction
The sole context is in this specific sub-folder in my MIT-licensed repo: https://github.com/outfox/fennecs/tree/main/fennecs
For the examples in this report, I added it as a Folder context most of the time

At the end I submitted it as a File context, with the entire C# contents of the directory concatenated into a markdown file, a small paragraph of opening instructions for the LLM, and with H2 for the file names. (this is my competing workflow with Claude)

![image](https://github.com/pieces-app/support/assets/8904620/90ea1dc4-7c38-41e7-a3db-c9b1b8f42aee)

It roughly looks like this. :)

## "Bug" / Unexpected Behaviour
The prompts and conversations are of extremely low quality.

I tried various models and keep getting very tangentially related, sometimes completely unrelated (different programming language, etc.), often gibberish-like suggestions. (interacting with the model is also bordering on the impossible)

![rider64_R7Z8HtvCmE](https://github.com/pieces-app/support/assets/8904620/86805cc4-9f50-4def-92e4-6dfd9d5cbbfa)

![image](https://github.com/pieces-app/support/assets/8904620/6e9f0288-8995-4a05-a912-44649a075d00)

![image](https://github.com/pieces-app/support/assets/8904620/893f816e-a8aa-4d91-83e6-487a7b33d939)

## Contrasting Expectation / Competition
To put this into perspective, this is the 1-shot I get with Claude 3 in my own workflow (which submits a simple markdown summary / concatenation of the code). This earns practically full marks in focus, correctness, and "understanding" of what a new user would like to do first with this library.

This, or roughly this, Quality of initial prompts would show me that Pieces has built a reasonable rapport and good bird's-eye view of the submitted context.

![image](https://github.com/pieces-app/support/assets/8904620/86b157a5-401b-45b9-b718-608cdaafda52)

**Comment by thygrrr** [comment]
# Actual Conversation for Prompt #1 With Pieces (GPT-4 - Gemini Pro didn't seem to accept the context)
This is a complete fail - this code for some generic ECS, which would operate quite differently from how the library in the context operates.

Out of fairness, I also submitted the context in the exact same form as I submitted it to Claude, but the result is practically identical and completely off-target.

![image](https://github.com/pieces-app/support/assets/8904620/b51261bb-0b63-42c9-8dfe-3e86bd54868a)


# Actual Conversation for Prompt #1 with Claude
This is pretty much full marks again - this example would work as written; if .Compile() were replaced with .Stream(). The enumeration Method isn't the main method, but the Repo itself actually doesn't contain an example how to use the relatively unique Stream Views efficiently. (I didn't add the hand-written documentation to the context)

![image](https://github.com/pieces-app/support/assets/8904620/8c803edb-31f4-4b6f-ac21-fe2f9e2fcc40)

**Comment by sam-at-pieces** [comment]
This has been resolved in the relevance updates at the start of July
