### ISSUE TITLE
GPT4 Often says that it cannot answer a question

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/support#25]
### Software

Desktop Application

### Operating System

macOS

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

While using the GPT4 model in the copilot, often it will say that it is 'Unable to answer that question as xyz is not in the context', even while there is context that is relevant to the question.

**Comment by Oliver-Turp** [comment]
![image](https://github.com/pieces-app/support/assets/55669423/2d9f37c5-4ac2-4b71-9dd4-7920c98e2381)
I hope following on from this, I'm seeing GPT4 is unable to read the message history. This would make follow up questions appear out of context as they wouldn't be as explicit as the opening question.

**Comment by seantiz** [comment]
I can relate to this, uploading snippets was something I thought would provide all the context it needs, but it sometimes struggles to give answers unless I copy and paste the entire context along with my question.

**Comment by sam-at-pieces** [comment]
This should have been resolved with our chat memory updates.
