### ISSUE TITLE
Anchors section under Captured Context is not loading properly

### ISSUE THREAD

**Issue by Astrodevil** [pieces-app/support#250]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.5

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Anchors section under Captured Context seems broken
Video - https://github.com/pieces-app/support/assets/73425223/72e12a55-71ed-4676-abd8-d666b2bc7df3

**Comment by mack-at-pieces** [comment]
Hey @Astrodevil - Can you please update to the latest version of the Pieces Desktop App - version 2.12.4, and let us know if this issue is still occurring? Thank you!

**Comment by Astrodevil** [comment]
Working fine now! @mack-at-pieces
