### ISSUE TITLE
WPE button not appearing in small tabs

### ISSUE THREAD

**Issue by Astrodevil** [pieces-app/support#252]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

Pieces OS 9.0.5

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

WPE button going out of box when opened in smaller tabs

![image](https://github.com/pieces-app/support/assets/73425223/b4493d88-0da9-47f7-b791-fd5cacfbaea9)
![image](https://github.com/pieces-app/support/assets/73425223/ddf00ad7-18ab-476b-94a7-54112310177a)

**Comment by mack-at-pieces** [comment]
Thanks @Astrodevil - Will be fixed in the next Desktop App release 👍🏼
