### ISSUE TITLE
Pieces OS Update Error

### ISSUE THREAD

**Issue by HarryLesnar24** [pieces-app/support#254]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.5

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When I start up my windows after some seconds Pieces OS run automatically the option **check for updates** background and got error in windows notification message like "Pieces OS Update Error Unknown Issue Error Happened" after while using system the Pieces OS triggered check for update option after some time repeatedly certain time gap between every trigger, and producing the same error again and again it's very disturbing if I tries to run manually check for update also the same issue arise
Source-I'm installed Pieces Developer and Pieces OS through Windows Store application

![image](https://github.com/pieces-app/support/assets/115340311/86c6cbbb-3b0e-4b96-8ef2-08c70e81ea2e)

**Comment by rosie-at-pieces** [comment]
Hi @HarryLesnar24 ! This is known bug that will be fixed before Thursday. Let us know if you still see that after Thursday!

**Comment by nathan-courtney-pieces** [comment]
This should be fixed now, will go out in the next Release on Thrusday. The issue is benign and is not actually a problem other than the annoyance of a notification.

**Comment by HarryLesnar24** [comment]
Hi @nathan-courtney-pieces and @rosie-at-pieces thanks for your timely response I can wait till for Friday and update you after update the Pieces OS application

**Comment by HarryLesnar24** [comment]
Hey @nathan-courtney-pieces and @rosie-at-pieces I got update today Pieces OS version 9.0.6 updated successfully and I tried to reproduce the same error now it's been fixed there is no error notification I get thanks for your support
