### ISSUE TITLE
Incorrect links for Visual Studio plugin

### ISSUE THREAD

**Issue by alexravenna** [pieces-app/support#261]
### Software

Marketing Site (pieces.app)

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Both the "Install" and "Learn More" links on the [plugins page](https://pieces.app/plugins) for the Visual Studio plugin point to the respective pages for the VS Code plugin.
![image](https://github.com/pieces-app/support/assets/29532881/27a6da3c-5135-40e2-a924-8612c018ad45)

**Comment by mack-at-pieces** [comment]
Hey @alexravenna 👋🏼  Thanks so much for bringing this to our attention. Our website team is on it and recently released a hotfix to address this issue.

In the meantime, were you able to find our resources for the Visual Studio plugin? Happy to help get you up and running if needed!

Here's a link to our docs: https://docs.pieces.app/extensions-plugins/visual-studio
Here's the link to the Visual Studio Marketplace Listing: https://marketplace.visualstudio.com/items?itemName=MeshIntelligentTechnologiesInc.PiecesVisualStudio

Thanks so much & lmk!
