### ISSUE TITLE
Pieces extension was updated or reloaded. Please reload the page.

### ISSUE THREAD

**Issue by RakeshPotnuru** [pieces-app/support#262]
### Software

Web Extension

### Operating System / Platform

macOS

### Your Pieces OS Version

9.0.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I keep seeing this pop up on every webpage randomly, even if I click ok, it's not closing until I check "Don't allow this page to display". This checkbox appears after I click ok multiple times.

<img width="322" alt="image" src="https://github.com/pieces-app/support/assets/70439799/55defd77-b4de-4799-85e5-731e4f58b058">

**Comment by rosie-at-pieces** [comment]
hi @RakeshPotnuru so sorry about this! we sent out a patch for this, you just have to refresh everything. so sorry for the inconvenience!
