### ISSUE TITLE
Trying to use "Save to Pieces" results in 'fspath' error

### ISSUE THREAD

**Issue by bmorrisondev** [pieces-app/support#263]
### Software

VS Code

### Operating System / Platform

macOS

### Your Pieces OS Version

9.0.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Using "Save to Pieces" from VS Code throws an fspath error. See attached video for steps. The repository this was being done on is at https://github.com/fullstack-chat/fullstack.chat

https://github.com/pieces-app/support/assets/4684030/77d205d1-efd7-45c9-98f4-9c7c801f88dd

**Comment by tsavo-at-pieces** [comment]
Hey @bmorrisondev ! Good looks here - super strange. Can't say I've seen that one but @caleb-at-pieces is on it! 

Should get this resolved over the weekend or early next week. Would you have 30 min to hop on with either him or the both of us in the coming days?

**Comment by caleb-at-pieces** [comment]
We plan to release a fix for this today! Keep a look out for the 1.16.2 version of the VS Code extension.

**Comment by caleb-at-pieces** [comment]
Hey @bmorrisondev we released a new version of the VS Code extension yesterday that should fix this bug. I'll go ahead and close this, please let me know or reopen this issue if you are still facing the same problem!
