### ISSUE TITLE
Appearance resets with each launch

### ISSUE THREAD

**Issue by GimpyHand** [pieces-app/support#277]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The software forgets settings when closed and relaunched on the same system. Notably, the appearance and theme settings like dark/light mode. I've encountered this on multiple systems.

**Comment by rosie-at-pieces** [comment]
Hey @GimpyHand so sorry you're experiencing this! We have resolved this in a staging build and it should be released on Monday in a desktop app release. Please let us know if you're still having this issue after updating!

**Comment by mack-at-pieces** [comment]
Hey @GimpyHand - Last week we released version 3.0.0 of the Desktop App, which should have resolved this issue. If you can confirm that would be awesome! Thanks!

**Comment by GimpyHand** [comment]
Hey @mack-at-pieces , the syncing of the library now works, but settings, such as dark/light mode, still reset upon closure of the app.

**Comment by mack-at-pieces** [comment]
@GimpyHand Great find. Just fixed and will be included with our patch release today 👍🏼
