### ISSUE TITLE
Cyrillic display problem

### ISSUE THREAD

**Issue by zemecom** [pieces-app/support#278]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

<img width="1075" alt="image" src="https://github.com/pieces-app/support/assets/12121385/b46ed526-f30d-43f7-8d3e-fd19308c90de">
![Без названия](https://github.com/pieces-app/support/assets/12121385/1c7c9505-4311-44ad-8cec-6167e97e8e29)

**Comment by rosie-at-pieces** [comment]
Hi @zemecom at this moment the Pieces app is only available in English when it comes to the UI. I'm so sorry for this inconvenience!

We have a [discussion](https://github.com/pieces-app/support/discussions/141) on this if you'd like to add your request for additional language support there!
