### ISSUE TITLE
Installation Issue on Windows

### ISSUE THREAD

**Issue by PierrunoYT** [pieces-app/support#280]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

Latest

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I tried to install with the Installer on Windows but it did not work for me. I never saw this type of installer. Then I tried to install both exes for Windows the OS and the Pieces for Developer but now I'm stuck in the Loading Screen 
![grafik](https://github.com/pieces-app/support/assets/95778421/1babded6-98e7-4a84-99e0-1d386393170e)

**Comment by nathan-courtney-pieces** [comment]
Hello @PierrunoYT 

Sorry to hear that you are having issues getting set up with Pieces!

The primary installation method uses Microsoft's App Installer. You may have an outdated version of it. You can check for updates to that through the Microsoft Store application, and best to restart your PC after words. 

As for using the alternative installation methods, (exe installer) those normally don't have any issues as they use an older technology compatible with most systems. Looks like you got those installed fine, but it appears Pieces OS isn't booting up properly if the Desktop app hangs on boot. 

Do you happen to have any Anti Virus Software on your machine? 

You can also check Windows Defender to see if it may have tried to block the application from booting up properly.

**Comment by PierrunoYT** [comment]
I'm not sure why it fails. I dont have any idea what to try.
