### ISSUE TITLE
Extension Panel for Pieces in VS Code Crashes if Pieces Desktop is Opened Before Launching VS Code

### ISSUE THREAD

**Issue by EveCrystali** [pieces-app/support#285]
### Software

Desktop Application, VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

## Description
The extension panel for Pieces Desktop crashes in VS Code, causing other extensions to crash as well when the Pieces Desktop application is launched before opening VS Code.

## Steps to Reproduce
1. Launch the Pieces Desktop application.
2. Open VS Code.
3. Observe the panel crash for the Pieces Desktop extension, followed by crashes of other extensions.

## Expected Behavior
The Pieces Desktop extension should load properly in VS Code regardless of whether the Pieces Desktop application is already running or not. Other extensions should remain unaffected.

## Actual Behavior
When the Pieces Desktop application is launched before opening VS Code, the extension panel for Pieces Desktop crashes, causing other extensions to crash as well.

## Environment
- **VS Code Version:** [1.90.2]
- **Pieces Desktop Version:** [2.12.5]
- **Operating System:** Windows 11 Pro 23H2 : [Windows_NT x64 10.0.22631]
- **Other Extensions Installed:** 
              _codeium.codeium;davidanson.vscode-markdownlint;donjayamanne.githistory;eamodio.gitlens;esbenp.prettier-vscode;github.vscode-pull-request-github;gruntfuggly.todo-tree;josefpihrt-vscode.roslynator;leonardssh.vscord;mechatroner.rainbow-csv;meshintelligenttechnologiesinc.pieces-vscode;mhutchie.git-graph;ms-ceintl.vscode-language-pack-fr;ms-dotnettools.csdevkit;ms-dotnettools.csharp;ms-dotnettools.vscode-dotnet-runtime;ms-iot.vscode-ros;ms-python.debugpy;ms-python.python;ms-python.vscode-pylance;ms-vscode.cpptools;postman.postman-for-vscode;shd101wyy.markdown-preview-enhanced;sonarsource.sonarlint-vscode;usernamehw.errorlens;visualstudioexptteam.intellicode-api-usage-examples;visualstudioexptteam.vscodeintellicode;yzhang.markdown-all-in-one_

## Logs

> Erreur de chargement de la vue web : Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

> 2024-07-03 11:01:59.041 [warning] Provider for scheme 'explainedPiecesSnippetPreview' is firing event for schema 'piecesSnippetPreview' which will be IGNORED

Thank you for your attention to this matter.

**Comment by caleb-at-pieces** [comment]
Hello @EveCrystali ! Thank you so much for pointing this out! Within the next day or so I will be able to take a look into this, and should be able to work a fix in for this soon!

Thanks again, and also: fantastic bug report! Super detailed!

**Comment by caleb-at-pieces** [comment]
I am not able to reproduce this, @EveCrystali is this still happening to you?

**Comment by EveCrystali** [comment]
@caleb-at-pieces 

> I am not able to reproduce this, @EveCrystali is this still happening to you?

No, it seems like, it is now fixed
