### ISSUE TITLE
Related Snippet Discovery failed

### ISSUE THREAD

**Issue by hra42** [pieces-app/support#291]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![CleanShot 2024-07-06 at 13 03 37](https://github.com/pieces-app/support/assets/44985923/b74e09c7-c602-4bfb-86ca-f404b47dd56a)

I get an error when I try to open this view. That is with every snippet.

**Comment by hra42** [comment]
sometimes I get this view too:
![CleanShot 2024-07-06 at 13 03 37](https://github.com/pieces-app/support/assets/44985923/101f221f-389b-4a94-9db8-ab199b99ef1a)

**Comment by VasuDev8110** [comment]
<img width="1023" alt="Screenshot 2024-07-08 at 3 54 39 PM" src="https://github.com/pieces-app/support/assets/118809473/65d65907-152d-44ae-9291-c48483e5e246">

Error from importing from github

**Comment by mark-at-pieces** [comment]
Hey @hra42 && @VasuDev8110 👋,

Thanks for adding this issue on Discovery within the Desktop application.

Would you 2 mind provide a bit more information around what repo/directory your provided to snippet discovery?

specifically:
1. a link to the directory/repo (github or zip) - would be most helpful
2. if unable to provide: a run down on all the types of languages within these directories/repos would be extremely helpful for debugging purposes!

Note: We have some fixes in our current staging build around Discovery, so would be awesome to see if these are still present when we release 10.0.0 on Tuesday evening!

**Comment by VasuDev8110** [comment]
I can't make to that step 
There are three options available 
Select file, select folder, import gists

And then when click on gists it shows this error

**Comment by hra42** [comment]
@mark-at-pieces my issue seems to be solved with the latest version. It works now and actually discovers similar snippets, great great stuff, major improvement to my workflow!

**Comment by mack-at-pieces** [comment]
Hey @hra42 @VasuDev8110 - If these issues weren't already resolved, they should have been with Pieces OS 10.1.0 and Pieces Desktop 3.1.0. Please let us know if you continue to have any issues. Thanks!
