### ISSUE TITLE
Error: Pieces for Developers Obsidian Plugin Requires Pieces OS Version 9.0.0 or Greater

### ISSUE THREAD

**Issue by stuXoon** [pieces-app/support#294]
### Software

Obsidian

### Operating System / Platform

macOS

### Your Pieces OS Version

10.0.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.
---

Greetings!

I'm having a bit of trouble with the Pieces plugin for Obsidian. It throws an error: "In order to use the Pieces for Developers Obsidian Plugin, you must have Pieces OS version 9.0.0 or greater! Please update your Pieces OS."

| <img width="323" alt="Screenshot 2024-07-10 at 17 52 48" src="https://github.com/pieces-app/support/assets/143246115/c6c87d6c-e5da-4596-9262-1d6fc76b1dc6"> | <img width="352" alt="Screenshot 2024-07-10 at 17 53 29" src="https://github.com/pieces-app/support/assets/143246115/a9ec6066-ff0d-47fd-9d95-7e6a7dbcfa7e"> |
|---|---|

Here are my system details:
- **Obsidian Version:** 1.6.5
- **Pieces OS Version:** 10.0.0
- **Pieces For Developers Obsidian Plugin Version:** 1.15.1
- **MacOS Version:** 14.2.1

Desktop Pieces App works normally.

Steps I took to try to fix the problem:
* Reinstalled the plugin
* Reinstalled PiecesOS
* Restarted my Mac

Unfortunately, none of these steps resolved the issue.

Additional screenshots:

| <img width="302" alt="Screenshot 2024-07-10 at 18 09 46" src="https://github.com/pieces-app/support/assets/143246115/ad863e14-cc0c-4f1d-a65e-c1688a7386da"> | <img width="297" alt="Screenshot 2024-07-10 at 18 09 56" src="https://github.com/pieces-app/support/assets/143246115/d2510c70-5a84-4988-ae64-b449052efd45"> |
|---|---|

I'd appreciate any guidance or suggestions to help resolve this issue. Thanks in advance for your assistance!

**Comment by mack-at-pieces** [comment]
Hey @stuXoon ! Thanks so much for reaching out. Super early this morning we released version 10.0.0 of Pieces OS, which has breaking changes that will require an update to the Obsidian plugin. Our team is working on this update as we speak and it should be live within the next couple hours.

We really appreciate your patience here and will let you know when the plugin is officially updated.

Thanks so much!

**Comment by stuXoon** [comment]
Nice to hear, @mack-at-pieces 👍
P.s. thanks for the quick reply and such a cool tool, I can't wait to try this integration with Obsidian!

**Comment by caleb-at-pieces** [comment]
Just a quick update here, this update is in the testing phase so if things go smoothly within the next hour or two we should have it shipped!

**Comment by caleb-at-pieces** [comment]
Just released Pieces Obsidian plugin 1.16.0, in a few minutes you should be able to update the Obsidian plugin and this issue will be resolved!
