### ISSUE TITLE
The functionality of adding a local project folder (using Win + WSL) is not working as expected

### ISSUE THREAD

**Issue by gabrielizalo** [pieces-app/support#296]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I am currently using Windows 11 Home Version 23H2 and rely on WSL for all of my development projects.

When attempting to install the latest Pieces Windows Suite and adding Local Projects through the 4-step Wizard process, I encountered an issue. Despite multiple attempts, I was unable to successfully add my main project. Although Pieces appeared to be functioning, the folder failed to be added after a few minutes.

Furthermore, I attempted to add the folder within the Pieces Windows application settings but was unable to locate the option.

I have included screenshots of Pieces, my WSL folder and Pieces Settings for reference:

PIECES WIZARD: 

![ZvFjifTU9X](https://github.com/pieces-app/support/assets/656353/444709ae-143f-4a8a-aba3-dd6cb89b017d)

MY WSL FOLDER:

![2a7e1tFvTG](https://github.com/pieces-app/support/assets/656353/8edc92b6-d29d-4a56-a706-9fad1affa60f)

PIECES SETTINGS:

![NYoGPm5FJI](https://github.com/pieces-app/support/assets/656353/306c039f-d029-433a-964f-252d889ae61c)

**Comment by caleb-at-pieces** [comment]
hello @gabrielizalo are you still facing this issue?

If so is it possible for you to provide me this folder? or at least describe the contents of what is within it?

**Comment by gabrielizalo** [comment]
I will close the issue. Thank you.
I uninstalled Pieces.
