### ISSUE TITLE
POS is at Version 10.0.0, but plugin is incompatible(Version Compatibility)

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/support#297]
### Software

Pieces OS, JetBrains, Obsidian, JupyterLab

### Operating System / Platform

macOS/ Windows/ Linux

### Your Pieces OS Version

10.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Attention:

if your version of PiecesOS is at 10.0.0, there are still a few plugins that are NOT released and compatible with PiecesOS breaking changes.

Those of the likes of 

Jetbrains - released in a day or 2 and is under review
JupyterLab - should be live today
Obsidian - should be live today

If you having issues with plugin compatibility and you plugin is not listed here.

Then please:

1. ensure your plugin is up-to-date
2. ensure your PiecesOS version is at 10.0.0 latest

Thanks you and dont hesitate to reach out!

Happy Coding🚀

**Comment by mark-at-pieces** [comment]
Note: if you are having any sort of version compatibility, plese just ensure POS and the respective plugin is up-to-date as well.

**Comment by luckycreationsindia** [comment]
Same here, Intellij idea Plugin is outdated or is not compatible with Pieces OS and all other software are up to date.

**Comment by borhanrahi** [comment]
I have issue with both vscode and pucharm and the app cant use it on vscode or pycharm any more after the update i did uninstalls all still not fixed for me  

![Screenshot_1](https://github.com/pieces-app/support/assets/40866382/8cd8ddc1-118a-4344-805c-73f0577872c2)
![image](https://github.com/pieces-app/support/assets/40866382/2f5e2c31-64a0-44a5-9d0a-f0c1119eebb9)

**Comment by mark-at-pieces** [comment]
> I have issue with both vscode and pucharm and the app cant use it on vscode or pycharm any more after the update i did uninstalls all still not fixed for me
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/40866382/347481004-8cd8ddc1-118a-4344-805c-73f0577872c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjgxMjAsIm5iZiI6MTcyMDYyNzgyMCwicGF0aCI6Ii80MDg2NjM4Mi8zNDc0ODEwMDQtOGNkOGRkYzEtMTE4YS00MzQ0LTgwNWMtNzNmMDU3Nzg3MmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWE2MTdiYTc0YmM5YzI2Njc5NjkxNmEwMjA0MWQ1YTQ3NGQyMTFkYjQ2ZDYzMDUyZGVjNjhkZGY3OTUzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ea5IklBueL4SQpXdRD6zqH0k8h34KFGb2bSZqV6hN4s) ![image](https://private-user-images.githubusercontent.com/40866382/347481162-2f5e2c31-64a0-44a5-9d0a-f0c1119eebb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjgxMjAsIm5iZiI6MTcyMDYyNzgyMCwicGF0aCI6Ii80MDg2NjM4Mi8zNDc0ODExNjItMmY1ZTJjMzEtNjRhMC00NGE1LTlkMGEtZjBjMTExOWVlYmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE2MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NzcyMDczM2M3ZmIyYmQ1NmZmZDViOTAyYmZkMWYyMzcyYWVjZWNiYzY5NDUwYzBmMjhjNzJmYzQ1N2Q5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w7uzh1dujMqWukyX8ZqA_icRoSoUR3dKM1gJB4uMZD4)

for vscode: you should have an update in the marketplace

for pycharm: this is a jb IDE so will not be ready for another day or 2 however I will add in a side loadable plugin build if yall want to try it:)

**Comment by mark-at-pieces** [comment]
@luckycreationsindia @borhanrahi here is the latest JB plugin build w/ 10.0.0 POS compatibility

[Pieces-9.0.0.zip](https://github.com/user-attachments/files/16165111/Pieces-9.0.0.zip)

**Comment by mark-at-pieces** [comment]
^^^ and if you go this route

here is instructions on installing from disk

https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by luckycreationsindia** [comment]
Thankyou

> @luckycreationsindia @borhanrahi here is the latest JB plugin build w/ 10.0.0 POS compatibility
> 
> [Pieces-9.0.0.zip](https://github.com/user-attachments/files/16165111/Pieces-9.0.0.zip)

**Comment by spiderJEDI** [comment]
I have same issue on VScode

**Comment by ariadnavenecia** [comment]
Same issue on jetbrains webstorm

**Comment by mriffey** [comment]
Seeing this: 
![CleanShot 2024-07-11 at 11 22 15@2x](https://github.com/pieces-app/support/assets/2301643/b3fb38cf-079e-4f73-8f3d-a1e12524954c)

Pieces is at 3.0.0 (MacOS). 

Desktop app says it is up to date. 

PyCharm plugin says it is at 8.2.0
![CleanShot 2024-07-11 at 11 26 41@2x](https://github.com/pieces-app/support/assets/2301643/50e10d52-0d2b-4c32-9035-946e341bb9fb)

![CleanShot 2024-07-11 at 11 28 10@2x](https://github.com/pieces-app/support/assets/2301643/a3eb741d-07a3-48b1-891a-9490efde386f)

PyCharm version: 
![CleanShot 2024-07-11 at 11 25 44@2x](https://github.com/pieces-app/support/assets/2301643/7d804138-5332-476b-8aae-f2e2245b16fd)

**Comment by ariadnavenecia** [comment]
Attaching more info from my side also, I installed the Apple Silicon package just yesterday:

![Screenshot 2024-07-10 at 8 34 02 PM](https://github.com/pieces-app/support/assets/100226746/9083e397-3cfb-4c5f-9d5a-255ec57c9025)
![Screenshot 2024-07-10 at 8 34 13 PM](https://github.com/pieces-app/support/assets/100226746/391dfa2e-0810-4f70-9bb8-55bfc32d7fc3)
![Screenshot 2024-07-10 at 8 34 38 PM](https://github.com/pieces-app/support/assets/100226746/ce15114a-edfd-4454-8499-39b68b866a57)
![Screenshot 2024-07-10 at 8 36 06 PM](https://github.com/pieces-app/support/assets/100226746/fd9deb7c-d35a-4117-aa81-8c6c8cc818b3)
<img width="344" alt="Screenshot 2024-07-10 at 8 37 10 PM" src="https://github.com/pieces-app/support/assets/100226746/3974461e-eb6b-4e5b-95d5-0f3d095fbfae">

**Comment by mack-at-pieces** [comment]
Hey everyone @ariadnavenecia @mriffey @spiderJEDI @luckycreationsindia - The Pieces JetBrains plugin with support for Pieces OS 10.0.0 (Version 9.0.2 of the plugin) should officially be live and available for you to update to. If you could please update to the latest and let us know if these issues continue that would be very helpful. Thanks!

**Comment by enermark** [comment]
9.0.2 cleared it up for me. Thanks!

**Comment by luckycreationsindia** [comment]
> Hey everyone @ariadnavenecia @mriffey @spiderJEDI @luckycreationsindia - The Pieces JetBrains plugin with support for Pieces OS 10.0.0 (Version 9.0.2 of the plugin) should officially be live and available for you to update to. If you could please update to the latest and let us know if these issues continue that would be very helpful. Thanks!

It's working now, thanks.
