### ISSUE TITLE
After Update Pieces Extensions are not working 

### ISSUE THREAD

**Issue by borhanrahi** [pieces-app/support#298]
### Software

Desktop Application, Pieces OS, VS Code, JetBrains

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I have Updated all the software then when I tried to use it on VSCode or Pycharm It's simply not working at all. 
 
![Screenshot_1](https://github.com/pieces-app/support/assets/40866382/e32ae4f2-2ad9-4800-a3df-1e59f4cd8d63)
![image](https://github.com/pieces-app/support/assets/40866382/7461f2f8-9a0c-47ac-b0ba-da56e87c120f)
![image](https://github.com/pieces-app/support/assets/40866382/a74790df-e5d0-486b-9d29-abe1355f32e2)
![image](https://github.com/pieces-app/support/assets/40866382/666cc0e2-0b0a-4cf4-9bb7-ce6746f9db66)

**Comment by mark-at-pieces** [comment]
duplicte issue here oging to close this for now, lets continue the conversation in 

https://github.com/pieces-app/support/issues/297

**Comment by mack-at-pieces** [comment]
Created a new issue to address the inability to launch the copilot here: #299
