### ISSUE TITLE
jsx file is not show in set context file

### ISSUE THREAD

**Issue by bikashd003** [pieces-app/support#301]
### Software

Pieces OS, VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

can't able to set jsx file as context

**Comment by mack-at-pieces** [comment]
Hey @bikashd003 - thanks for bringing this to our attention. The team will look into this and see if we can enable support for this in an upcoming patch release. We'll report back what we find. Thanks!

**Comment by bikashd003** [comment]
@mack-at-pieces thanks for solving this issue
