### ISSUE TITLE
PiecesOS crashes when starting Pieces for Devs Desktop App

### ISSUE THREAD

**Issue by lrmtheboss** [pieces-app/support#303]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

After Updating pieces OS to 10.0.0 and pieces for devs desktop app to 3.0.0. Pieces OS appears to start fine but when I open Pieces for Devs Desktop, Pieces OS crashes. No errors are logged to the log file besides can't connect from Pieces for Devs Desktop once Pieces OS crashes.

I've tried uninstalling both, clearing all files and related registry keys from my system, and then reinstalling. The issue still occurs.
I also tried updating windows and doing a full restart.

**Comment by shivay-at-pieces** [comment]
Hey @lrmtheboss thanks for reporting, the team is looking into the issue and will resolve it!

**Comment by rosie-at-pieces** [comment]
@lrmtheboss so sorry you're experiencing this issue! to help us with troubleshooting, can you please tell us the specs of your machine?

**Comment by lrmtheboss** [comment]
Hp gaming pavilion laptop
Intel i5-8300H (base 2.3GH, max 3..4GH, average 3.2GH)
32GB 2667mhz ram
Nvidia GTX 1050TI
All solid-state storage
Windows 10 Version 22H2 Ob build 1904

**Comment by lrmtheboss** [comment]
https://drive.google.com/file/d/1SN_dvZKTiDHzurSl5SqbEHwfTQdPUB_x/view?usp=sharing

**Comment by thecatontheceiling** [comment]
I have the same issue, video of it here:
https://cdn.discordapp.com/attachments/1116093095981883402/1263029920024756305/2024-07-17_03-09-50.mp4?ex=6698bfc6&is=66976e46&hm=e7617be0094f038fa0fa8e2c7c9a988509083bd650acfbaf79abe1cc1d471401&

I'm running Windows 10 with the latest version of Pieces OS and Pieces for Developers as of today.

**Comment by jose-PreG** [comment]
Same here also running Windows 10 Enterprise LTSC. 
NVIDIA Quadro P620 i5-9400H.

**Comment by nathan-courtney-pieces** [comment]
Can confirm this is an issue with our alternative installation method for Windows. 

A patch is in progress. 

In the meantime this can be circumvented by using the primary installation method found on our Website, or through this direct link here: https://builds.pieces.app/stages/production/appinstaller/os_server.appinstaller.

Recommendation is to uninstall the current distribution before hand to prevent any conflicts. All user data is separate from the installation found in your User\Documents folder.

**Comment by thecatontheceiling** [comment]
I'll wait for a patch, I'm not installing Microsoft store just to get one app

thank you

**Comment by nathan-courtney-pieces** [comment]
The patch should be pushed now. Relaunching Pieces OS should trigger the update process

**Comment by lrmtheboss** [comment]
This is fixed for me as of versions 10.0.2 and 3.0.2. Thanks, everyone.
