### ISSUE TITLE
Error: update not Found 

### ISSUE THREAD

**Issue by BeltranMal** [pieces-app/support#306]
### Software

Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

when i tried to update pieces OS it just appears Error: Update Not Found 
![image](https://github.com/user-attachments/assets/4852318f-b8b3-4d6a-8245-385e1d5bce4f)

**Comment by shivay-at-pieces** [comment]
Hey @BeltranMal thanks for raising this issue. We are aware that some of the Pieces services are currently down including the website and the update functionality. We’re very sorry for the inconvenience this may have caused. The team is working to resolve the issues as quickly as possible.

**Comment by shivay-at-pieces** [comment]
Hey @BeltranMal  the issue is resolved now. Let me know if you still face any issues!
