### ISSUE TITLE
DNS issue in https://pieces.app/ domain (Unable to load) Sharing Snippet not working

### ISSUE THREAD

**Issue by ahuja2666** [pieces-app/support#308]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

latest

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

https://pieces.app/ domain is not loading thats why unable to share the snippets like https://harshitahuja.pieces.cloud/?p=9f394fac5d

**Comment by shivay-at-pieces** [comment]
Hey @ahuja2666 thanks for raising this issue. We are aware that some of the Pieces services are currently down. We’re very sorry for the inconvenience this may have caused. The team is working to resolve the issues as quickly as possible.

**Comment by shivay-at-pieces** [comment]
Hey @ahuja2666 the issue is resolved now. Let me know if you still face any issues!

**Comment by polyglotdev** [comment]
> Hey @ahuja2666 the issue is resolved now. Let me know if you still face any issues!

I will restart and try it again. It was broken still about 20 minutes ago.

**Comment by ahuja2666** [comment]
It's working. Thanks for your quick prompt @shivay-at-pieces

**Comment by polyglotdev** [comment]
Yep working again!
