### ISSUE TITLE
Linux Manjaro KDE Arch : Desktop, VS and Jetbrains : Pieces is not working  - Connected but none of the AI Models are working

### ISSUE THREAD

**Issue by Kether180** [pieces-app/support#31]
### Software

Desktop Application

### Operating System

Linux

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

- Pieces is not working on Linux Manjaro Arch - Connected but none of the AI Models are working.

- Pieces OS Desktop and Plugging  in VS and Intellij says  :  I'm sorry. Something went wrong with processing. Please wait a few seconds and try again, or contact support@pieces.app 🙂

**Comment by rosie-at-pieces** [comment]
Hey there, so sorry you're having trouble.

Can you please specify which LLM you are attempting to use? Cloud or local?

**Comment by Kether180** [comment]
@rosie-at-pieces If I try to use any Model it doesn't work . When I open the app that tells that pieces is connected the app goes off.

The desktop app pops up but the GP4 Model is not working. @caleb-at-pieces 

I'm sorry. Something went wrong with processing. Please wait a few seconds and try again, or contact support@pieces.app 🙂

**Comment by Kether180** [comment]
it is actually not working at all on linux manjaro

**Comment by rosie-at-pieces** [comment]
hey @Kether180 the problem here is likely due to Manjaro, Pieces is currently only officially supporting ubuntu or ubuntu-based distros. we have a discussion about it [here](https://github.com/pieces-app/support/discussions/14) if you want to participate in that conversation!

**Comment by im-sayann** [comment]
Hello, i am using zorin os latest build, i tried to install pieces stuffs its installed successfully, but when i open the pieces os app its just showing the loading screen and looping, when i open the pieces dev app, the app says "Missing Data" and lots of compatibility details....

![Screenshot from 2024-07-24 23-19-29](https://github.com/user-attachments/assets/99aa994a-8156-415b-bd6f-b4e3621e7b55)
