### ISSUE TITLE
Having issues with Vietnamese font

### ISSUE THREAD

**Issue by VanPhuLongDev** [pieces-app/support#312]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The app's interface is experiencing errors when I use Vietnamese
![image](https://github.com/user-attachments/assets/caa7b499-3c9e-4445-a44f-a420b33fbc42)

**Comment by rosie-at-pieces** [comment]
Hi @VanPhuLongDev so sorry - we don't have multi-lingual support so we can't guarantee success with languages other than English. However, this is on our roadmap and we'll address this when we can! So sorry for the inconvenience.
