### ISSUE TITLE
WPE context after update to latest version

### ISSUE THREAD

**Issue by hra42** [pieces-app/support#314]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

10.0.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

after I updated to the latest version WPE does seem to have no effect for example

![image](https://github.com/user-attachments/assets/4cb45db8-7167-45df-a5d1-57de7a46bb66)
(used Claude 3.5)
or
![image](https://github.com/user-attachments/assets/7b370457-7dde-4bf3-ac62-f14771a98e7c)
(This is with google gemini)

![image](https://github.com/user-attachments/assets/a0bb56d6-3377-4714-8f5f-f917342d7eae)
when questioned directly it gave weeks old context

after I restarted my mac it seem to be solved
![image](https://github.com/user-attachments/assets/429e9581-343e-44a4-a62d-3d9d2aedc702)

**Comment by hra42** [comment]
Hi @sam-at-pieces 

No in the last few days it worked without any flaw. @shivay-at-pieces mentioned that the qdrantdb hadn't properly initialed, I could send you the logs if that helps.

**Comment by sam-at-pieces** [comment]
That's great news @hra42 although I would like to take a look at that initialization issue, would love to see those logs if you could pass them over!

**Comment by sam-at-pieces** [comment]
@rosie-at-pieces I will close this issue as the WPE seems to be working as expected - will open another around qdrant initialization after taking a peak at the logs if required.

**Comment by hra42** [comment]
@sam-at-pieces here you go
POS:
[log-07142024.txt](https://github.com/user-attachments/files/16281886/log-07142024.txt)
[tesseract.log](https://github.com/user-attachments/files/16281888/tesseract.log)

PFD:
[log-07142024.txt](https://github.com/user-attachments/files/16281892/log-07142024.txt)
