### ISSUE TITLE
"I'm sorry, something went wrong with processing..." response from Copilot when using VSCode or JetBrains copilot actions 

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#316]
### Software

Pieces OS, VS Code, JetBrains

### Operating System / Platform

macOS

### Your Pieces OS Version

10.0.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

A few users are experiencing an issue when they start a copilot chat with one of the Pieces actions including "Ask Copilot" "Pieces Fix" "Pieces Explain" and "Pieces Comment"

**Comment by mack-at-pieces** [comment]
The fix for this was released today in Pieces OS 10.0.2 and Pieces Desktop 3.0.2. Please refresh your instances of VS Code/JetBrains and try again. Thanks!
