### ISSUE TITLE
Copilot not responding/freezing after using Hard Reset Runtime

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#317]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

10.0.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The copilot gives a forever "..." when you send a message after using the Hard Reset Runtime functionality

**Comment by mack-at-pieces** [comment]
Update: The team identified an issue in the "Hard-Reset Active Runtime" flow that was causing the copilot to forever hang when sending a new message afterwards.

This issue has been fixed and is in the queue to be released in a patch this week. We will continue to update this issue accordingly.

Thank you!

**Comment by mack-at-pieces** [comment]
The fix for this was released today with Pieces OS 10.0.2 & Pieces Desktop 3.0.2. Closing this issue for now.
