### ISSUE TITLE
Can't Paste Into Pieces Copilot - Manage Copilot Context | Websites

### ISSUE THREAD

**Issue by anchapin** [pieces-app/support#319]
### Software

VS Code

### Operating System / Platform

macOS

### Your Pieces OS Version

10.0.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![image](https://github.com/user-attachments/assets/8164d770-e56c-44de-9d28-43c1320ff62d)
In this window, I'm not able to paste in a web url. I tried CMD + v and right click to paste (this doesn't appear to be an option), but I can't get the url to paste in.

**Comment by mack-at-pieces** [comment]
Thanks @anchapin - The team is looking into this and hopes to have a fix released next week 👍🏼

**Comment by caleb-at-pieces** [comment]
Hi @anchapin I've seen this issue on one other machine, and it seemed that following these steps fixed the issue:

1. uninstall the pieces for vscode extension
2. close vscode
3. open vscode
4. install the pieces for vscode extension

Can you please try these and let me know if it works?

**Comment by anchapin** [comment]
Hi Caleb, I'm on vacation this week but can check this on Monday.

**Comment by caleb-at-pieces** [comment]
This should be resolved with the latest version (1.18.0) of the VS Code extension as well as 10.1.5 Pieces OS.
