### ISSUE TITLE
Unable to Connect to PiecesOS OR PiecesOS crashing - Windows

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#324]
We have found an issue with the exe installer for Windows. We have a fix queued up for release but if you'd like to resolve this now please uninstall Pieces and PiecesOS entirely, and reinstall using the [Pieces Suite Installer](https://docs.pieces.app/installation-getting-started/windows). This is the generally recommended way of installing Pieces anyways and might prevent future issues!

**Comment by nathan-courtney-pieces** [comment]
This should now be resolved
