### ISSUE TITLE
Copy / Paste issues

### ISSUE THREAD

**Issue by g0ldyy** [pieces-app/support#328]
### Software

VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

- It's impossible to copy just part of an AI response (if you select and press CTRL + C, it simply won't copy anything)
- It's impossible to paste several things into the prompt space (if I paste a first piece of code it works, if I try to paste something else it removes everything I've put in previously)

**Comment by caleb-at-pieces** [comment]
Hello @g0ldyy thank you for reaching out to us about this.

The team is highly aware of these issues affecting copy + paste and we are working hard to resolve them ASAP! We appreciate your patience and should have an update out for this soon!

**Comment by caleb-at-pieces** [comment]
This should be resolved with the latest releases of the VS Code extension as well as Pieces OS. Thanks for reaching out!
