### ISSUE TITLE
The Pieces OS window app seems buggy, shows a blank screen only

### ISSUE THREAD

**Issue by maxacarvalho** [pieces-app/support#330]
### Software

Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

Pieces OS 10.0.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi,

I just installed the Pieces app and the Pieces OS seems a little off.  
When I click o the icon it shows a blank screen and nothing more. The only way to close it is by using brute force.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/406080ea-7fe6-4a8b-b2a3-ed497b771b7a">

**Comment by rosie-at-pieces** [comment]
hi @maxacarvalho 👋  so sorry you ran into this problem! this should be resolved now with PiecesOS version 10.0.3. Let me know if it isn't!

**Comment by maxacarvalho** [comment]
Same issue:

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/4bb350c2-e8aa-4668-883d-2166aa054036">
