### ISSUE TITLE
UI not following the Obsidian Theme

### ISSUE THREAD

**Issue by PriyanshuMallick** [pieces-app/support#333]
### Software

Obsidian

### Operating System / Platform

Windows

### Your Pieces OS Version

v10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![image](https://github.com/user-attachments/assets/c1a555c2-d58c-45ba-a00d-529a9dc483e9)

The Pieces Plugin for Obsidian is not following the UI Theme as it did in the previous updates.

I'm currently using the [Border](https://github.com/Akifyss/obsidian-border) Theme

It also doesn't work with some other themes like
- [Encore](https://github.com/carbonateb/obsidian-encore-theme)
- [Notation 2](https://github.com/Bluemoondragon07/obsidian-notation-2)
- [Solitude](https://github.com/KyleKlus/solitude-obsidian-theme)
- [Dracula Gemini](https://github.com/clbn/dracula-gemini)

But It doesn't work for
- Default
- [Atom](https://github.com/kognise/obsidian-atom)
- [Tokyo Night](https://github.com/tcmmichaelb139/obsidian-tokyonight)
- [Simple](https://github.com/diegoeis/simple-obsidian)

**Comment by caleb-at-pieces** [comment]
Hello @PriyanshuMallick thanks for bringing this to my attention. I'll work some more on this soon and get this resolved.

In the mean time, if you are able, I recommend using themes or modifying your favorite theme to only use colors in the following formats:
- rgb()
- rgba()
- #RRGGBB
- #AARRGGBB

I will be sure to make another response here when the fix is out!

**Comment by PriyanshuMallick** [comment]
Hey @caleb-at-pieces , I just skimmed through [Border's theme.css file](https://github.com/Akifyss/obsidian-border/blob/main/theme.css) most of them where in `rgb()` or `rgba()` format but some of them also used `hsl()`. 

Hope this is fixed soon. Great work on Pieces BTW I love it.

**Comment by caleb-at-pieces** [comment]
Hello @PriyanshuMallick thank you for the kind words :). I've managed to resolve this in my own development environment, here's a screenshot of the new theming using the Border theme:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8a3e1197-4b5a-43c6-a833-a2b848e99fdc">

**Comment by caleb-at-pieces** [comment]
Update here, I've just released the 1.17.1 version of the Pieces Obsidian plugin that should end up resolving this issue, please let me know how it goes! Thanks again for letting is know about this.
