### ISSUE TITLE
Pieces OS stuck on start

### ISSUE THREAD

**Issue by JeffreyAReyes** [pieces-app/support#336]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Pieces OS stuck on the start screen with a Loading Pieces OS error... message

**Comment by JeffreyAReyes** [comment]
![image](https://github.com/user-attachments/assets/503bce2a-c377-4ea5-a742-92c035913b79)

**Comment by JeffreyAReyes** [comment]
Good day! 
Just resolved the issue. Windows Security blocks Pieces OS. 

![image](https://github.com/user-attachments/assets/1016a20f-adba-4c86-b530-eee502262d94)

**Comment by rosie-at-pieces** [comment]
@JeffreyAReyes glad you figured this out! yes - security programs can indeed block Pieces occasionally.
