### ISSUE TITLE
Pieces Onboarding Cannot Zoom in/Zoom out

### ISSUE THREAD

**Issue by choir27** [pieces-app/support#345]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The user should be able to zoom out/in the Pieces onboarding screens.

## Steps to reproduce:

1. Install Pieces Desktop and Pieces OS
2. Got to any page in the onboarding and try to zoom in or zoom out using `Ctr` + `+` or `Ctr` + `-`

If the user is able to zoom in/out in the main application, they should also be able to do the same in the onboarding screens, for both accessibility and consistency purposes.

![354743015-a7b570cd-de25-48c6-8bf1-8f3479684c6b](https://github.com/user-attachments/assets/69c76db9-7287-4a69-bfb7-878a4fc79ed2)

## Intended behaviour:
You should be able to zoom in or zoom out in any of the onboarding pages

## What is actually happening:
Nothing happens and the screen stay the same

**Comment by sam-p-at-pieces** [comment]
@choir27 
Good find! The fix for this will be in the next release
