### ISSUE TITLE
Pieces Copilot now working from VS Code

### ISSUE THREAD

**Issue by moofazzel** [pieces-app/support#346]
### Software

VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

Pieces OS 10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When I try to access Pieces Copilot from VS Code, it shows an error. And not working open AI cloud from vs code and Pieces OS 
![image](https://github.com/user-attachments/assets/a3c7096a-9ff1-4d4c-a3ba-e70d92e8a69e)

**Comment by caleb-at-pieces** [comment]
Hey @moofazzel thank you for reaching out to us about this issue.

Can you please let me know which model you are using?

A workaround for this issue is to either reset the active runtime, or restart Pieces OS. https://docs.pieces.app/faq#resetting-the-copilot-runtime

**Comment by mark-at-pieces** [comment]
@moofazzel I would also double check that if you have a firewall on your machine that Pieces requests are not getting blocked.

if this issue continues to persist please feel free to schedule some time w/ myself

https://calendar.app.google/T2d9gTE4rRMnyH3dA

**Comment by rosie-at-pieces** [comment]
this issue is related to [this issue](https://github.com/pieces-app/support/issues/351) so i am going to close this one as duplicate, please refer to that ticket if you are experiencing this issue!

**Comment by rosie-at-pieces** [comment]
Duplicate of #351
