### ISSUE TITLE
live context not working

### ISSUE THREAD

**Issue by Niketangoyal** [pieces-app/support#348]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

hey, my pieces live context not working after turn on live context. and it give very late response for very simple questions please help me

**Comment by Niketangoyal** [comment]
i am using GPT 4o. and this issue is also happening when i do not turn on
live context. This gives only answers to simple questions like chatGPT. and
it gives very slow responses.

**Comment by rosie-at-pieces** [comment]
@Niketangoyal we have found a small bug with the Live Context, a fix will go out with the next release of PiecesOS, which should be next week! Please let us know if that resolves it. 

As far as the slow responses - can you please share a video of what is happening with us? You can also set up a call with Mark using this link: https://calendar.app.google/T2d9gTE4rRMnyH3dA

**Comment by mack-at-pieces** [comment]
Hey @Niketangoyal yesterday we released Pieces OS 10.1.0 and Pieces Desktop 3.1.0 - can you please update and let us know if you are still having issues? Thanks!

**Comment by rosie-at-pieces** [comment]
Closing due to no response from the user.

**Comment by gauravgoel11** [comment]
Instead of the live context, I am viewing the LTM context in my Pieces Desktop app. Can you help me with this? How can I view the live context feature in my Pieces Desktop app on Windows? I am using the GPT-4.0 model.
