### ISSUE TITLE
My peices os is not getting launch

### ISSUE THREAD

**Issue by Hemantsharma1000** [pieces-app/support#349]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

3.0.2

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![Screenshot 2024-08-08 151320](https://github.com/user-attachments/assets/9e961ae6-83df-418a-8e14-62e977b53e2e)
Exception: Failed to open PiecesOs, Unable to find the proper data directory. I also restarted the machine also

**Comment by rosie-at-pieces** [comment]
Hi @Hemantsharma1000 this is the same issue as previous one that @nathan-courtney-pieces is responding to, please [check there and try the solution](https://github.com/pieces-app/support/issues/344). If the suggested solution doesn't work please comment on the other ticket.

Will close this as a duplicate.
