### ISSUE TITLE
Pieces OS Update Error

### ISSUE THREAD

**Issue by REXREUS** [pieces-app/support#356]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![gambar_2024-08-12_224009636](https://github.com/user-attachments/assets/e4ba50c0-1896-4c3f-8928-5f9ec5f192cc)
as you can see in the picture above pieces OS always displays an update error notification and after a few seconds pieces OS starts it will stop. I've tried reinstalling, opening the firewall for the OS, and setting controlled folder access and even turning off Windows Defender during installation but the results are always the same.

**Comment by rosie-at-pieces** [comment]
Hi @ardiferdiansah07 thanks for submitting this! We've created a fix for this and it will be released in the next PiecesOS version (10.1.0) hopefully tomorrow evening EST (8/13/24)!

**Comment by Pradyumn1729** [comment]
even Iam having the same error as above mentioned 
it is not updating at all 
it is just checking for updates 
and is checking only 
not getting updated at all 
please sort it out

**Comment by Pradyumn1729** [comment]
Hlo sir...
No right now iam not facing any issue right now...
But I will let u know if any ...
Thank you sir
