### ISSUE TITLE
piece client bug 

### ISSUE THREAD

**Issue by hamzouzou** [pieces-app/support#359]
### Software

Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

Pieces CLI version: 1.1.0

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi, 
commande **pieces run**
return this error : 
Unhandled exception:
Null check operator used on a null value
#0      Classification.fromJson (package:runtime_common_library/model/classification.dart:84)
#1      Format.fromJson (package:runtime_common_library/model/format.dart:278)
#2      Format.listFromJson (package:runtime_common_library/model/format.dart:304)
#3      AssetFormats.fromJson (package:runtime_common_library/model/asset_formats.dart:83)
#4      Asset.fromJson (package:runtime_common_library/model/asset.dart:305)
#5      Asset.listFromJson (package:runtime_common_library/model/asset.dart:326)
#6      Assets.fromJson (package:runtime_common_library/model/assets.dart:76)
#7      Cacher.cache (package:pieces_cli/src/util/cacher.dart:86)
<asynchronous suspension>
#8      _initChecks (file:///Users/runner/work/pieces-cli/pieces-cli/bin/main.dart:109)
<asynchronous suspension>
#9      main (file:///Users/runner/work/pieces-cli/pieces-cli/bin/main.dart:27)
<asynchronous suspension>

**Comment by rosie-at-pieces** [comment]
hi @hamzouzou so sorry but the CLI agent is not yet ready to be downloaded on Homebrew, it should be ready in a day or two. in the meantime it is available on pypi!

**Comment by hamzouzou** [comment]
No worries, thank you for the quick reply :)

**Comment by rosie-at-pieces** [comment]
Apologies for never following up here but the CLI agent is now available using homebrew! Please let us know if you run into any issues, please note that we are still working on performance improvements for this as well.
