### ISSUE TITLE
Pieces OS crashing after launch

### ISSUE THREAD

**Issue by Rapl4** [pieces-app/support#360]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Pieces OS crashing around 15 seconds after launch. 
http://localhost:1000/.well-known/health says "ok"
Around 3 seconds before it crashes, this sound plays https://www.youtube.com/watch?v=4VtBUqHh3HU

**Comment by rosie-at-pieces** [comment]
@Rapl4 that response means PiecesOS in good shape and not actually crashing. can you please check your task bar and see if PiecesOS is there, and if so can you launch the Pieces Desktop App from it?

If not - can you please respond with a screenshot or video of what is happening?

**Comment by Rapl4** [comment]
It only says ok before it crashes but then it doesn't work, Also I get the loading cursor seconds before crash.
Not sure if this is related but Pieces Qdrant Server process still runs fine.

**Comment by Rapl4** [comment]
Also, while it is still running for those 15 seconds, nothing that requires internet works in the Pieces Desktop app

**Comment by rosie-at-pieces** [comment]
Ok, so sorry to hear. Let's try a few standard troubleshooting steps and then if those don't work let's hop on a call!

1. Restart your machine
2. Uninstall and reinstall Pieces
3. Ensure you are entirely up to date for PiecesOS and the Pieces Desktop App. 

If still still persists, please use [this link](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2iaRWpd1kA2k_xg2KrVi_jiTHo0POiMZSI9WAYsxs5jJ9sU2Rd2zKitLuSFd7l3FhatGzy5Vgt) to set up a call with Mark.

**Comment by Rapl4** [comment]
It crashes during memory process optimization

**Comment by rosie-at-pieces** [comment]
@Rapl4 we released a PiecesOS update yesterday, are you still experiencing this after updating to PiecesOS 10.1.0?

**Comment by Rapl4** [comment]
I am

**Comment by rosie-at-pieces** [comment]
Ok, so sorry to hear! Can you please use the link above to connect with Mark?

**Comment by Rapl4** [comment]
I don't need help anymore, I started using my second laptop for Pieces which it works fine on
