### ISSUE TITLE
Font error with Vietnamese

### ISSUE THREAD

**Issue by beso-dev18** [pieces-app/support#361]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

10.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I am Vietnamese. I want to use my native language when working with Pieces. Is there any way to fix the font error as below?
Thank you.
![image](https://github.com/user-attachments/assets/bf5b52a7-9b18-4eb5-850c-d01eb407ea93)

**Comment by rosie-at-pieces** [comment]
Hi @beso-dev18 our apologies but at this moment we only support English. There is an [open discussion ](https://github.com/pieces-app/support/discussions/141)about this if you'd like to join there!
