### ISSUE TITLE
PiecesOS won't start up after update

### ISSUE THREAD

**Issue by tazmaniax** [pieces-app/support#363]
### Software

Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

Not sure because in between update

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I received a notification in PiecesOS of an update. I did the update but now it doesn't appear to complete the startup. I tried to reinstall through Homebrew but I get the same problem. This is on macOS Sequoia public beta.

![CleanShot 2024-08-15 at 08 54 03@2x](https://github.com/user-attachments/assets/ac02b0cd-8014-4853-b395-91dc12378d0a)
![CleanShot 2024-08-15 at 08 53 50@2x](https://github.com/user-attachments/assets/180a35ac-e3df-404a-85aa-991ccf5406d1)
![CleanShot 2024-08-15 at 08 53 20@2x](https://github.com/user-attachments/assets/7fdae571-d746-49b9-8ff5-d600930f126c)

**Comment by mark-at-pieces** [comment]
Note: will be fixed in 10.1.1, thank you for reaching out(release will be live in an hour)

**Comment by mark-at-pieces** [comment]
10.1.1 is going out right now, please check you are on the latest version in 15 min! If this does not resolve your issue please let me know! Hope you have a great day!

**Comment by abhijitWebDev** [comment]
@mark-at-pieces issue is resolved, pieces is working fine after the update.

**Comment by mark-at-pieces** [comment]
@abhijitWebDev legendary thank you again

**Comment by tazmaniax** [comment]
Thanks @abhijitWebDev @mark-at-pieces thanks for the amazingly quick turnaround. How do I update the PiecesOS?

**Comment by abhijitWebDev** [comment]
@tazmaniax do you have Pieces suite, if not install that, its easier to update that way.

**Comment by tazmaniax** [comment]
@abhijitWebDev is that the desktop app or something else? Do you have a link? Thanks

**Comment by abhijitWebDev** [comment]
@tazmaniax you can download pieces os update, by clicking the p icon 
you can view it in the below link, how to update it.
https://docs.pieces.app/faq#pieces-os

**Comment by tazmaniax** [comment]
@abhijitWebDev if you're referring to the "P" icon in the macOS menu bar, then all I get is an empty white box. Selecting the reload button in the bottom right makes no difference

![CleanShot 2024-08-15 at 20 04 51@2x](https://github.com/user-attachments/assets/288e70c7-8d16-458e-995e-460235bd9084)

**Comment by abhijitWebDev** [comment]
@tazmaniax try re installing the pieces os , that should work, ie first uninstall first and again install it.

**Comment by tazmaniax** [comment]
@abhijitWebDev got there, thanks!
