### ISSUE TITLE
Copilot can't understand context from file or folder

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#367]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.1

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

We found a problem with file/folder context in the copilot and working on a fix, patch should be out today!

**Comment by mack-at-pieces** [comment]
Issue was addressed in Pieces OS 10.1.2 and Pieces Desktop App 3.1.2. Please update and try again :) Let us know if you experience issues.
