### ISSUE TITLE
[Bug] Pieces for JetBrains IDEs is not compatible with current versions

### ISSUE THREAD

**Issue by MovGP0** [pieces-app/support#370]
### Software

JetBrains

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The Pieces plugin for JetBrains IDEs is not compatible with the current version of the IDE (Build `242`):

![image](https://github.com/user-attachments/assets/7ed14677-c135-44ac-8364-c5f04b8da06f)

### Additional Information

```
JetBrains Rider 2024.2
Build #RD-242.20224.401, built on August 14, 2024
Licensed to Johann Dirry
Subscription is active until November 4, 2024.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
```

**Comment by caleb-at-pieces** [comment]
Hey @MovGP0 , thanks for reaching out to us about this issue, we should have a resolution for this sometime this week!

**Comment by madstt** [comment]
Any news on this issue?

**Comment by caleb-at-pieces** [comment]
We have a build that is compatible with the new version, we are just in the testing phase, getting ready to officially release it. I suspect we will send that build to Jetbrains for approval today.

**Comment by caleb-at-pieces** [comment]
We have publish the plugin to the jetbrains team for approval, it should be ready by next tuesday. Appreciate the patience on resolving this. Also FYI you will also need to update your Pieces OS 10.1.5 (coming out today) in order to use the next version of the Jetbrains plugin.
