### ISSUE TITLE
Chinese shows as garbled

### ISSUE THREAD

**Issue by bennyz327** [pieces-app/support#373]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

Pieces OS 10.1.2

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

#### Step:
1. download windows installers and install
2. connect to Github+Google+chatgpt, then talk to chatgpt with chinese

#### Bug describe
My manul input and gpt response text is correct
But the suggestd question and output is garbled

See screenshots on [this issue](https://github.com/pieces-app/support/issues/103#issuecomment-2298424237_)

**Comment by rosie-at-pieces** [comment]
Hey @bennyz327 it looks like OpenAI is having a decoding issue for non-english characters - [they had one previously that was resolved](https://community.openai.com/t/gpt-4-1106-preview-messes-up-function-call-parameters-encoding/478500/98?page=2), but it looks like a recent update might have caused it to come back.

We'll keep an eye on this, but unfortunately not much we can do. The other models like Claude or Gemini (or any of the local ones) shouldn't have this problem. Let me know if you still experience this with other models!

**Comment by bennyz327** [comment]
I downloaded the recommended local LLM and restarted the OS and App.
The recommended question are still garbled.
![image](https://github.com/user-attachments/assets/5b145779-52e8-4741-9170-bbc9cd483b2b)

**Comment by bennyz327** [comment]
if I press the recommended response button, the pieces-app gets stuck while generating the response until I force close it.

![image](https://github.com/user-attachments/assets/43afa282-d64f-47c8-9d3a-3f82ef9dc7cc)

**Comment by rosie-at-pieces** [comment]
Hi @bennyz327 we have found a fix for this, please keep an eye out in the next release!

**Comment by mack-at-pieces** [comment]
Hey @bennyz327 would you be willing to give this another try today and let us know the result? Thanks!

**Comment by rosie-at-pieces** [comment]
Closing this as we received no response from user
