### ISSUE TITLE
Can't select text from Pieces Desktop

### ISSUE THREAD

**Issue by davidbdyer** [pieces-app/support#377]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I can't select text from the Pieces Desktop app.

**Comment by mack-at-pieces** [comment]
Hi @davidbdyer We are trying to solve an issue with text selection upon bootup in the copilot within the Desktop App. Is this the issue you're experiencing? If so, to get around it, you can first double-tap on a keyword to toggle the focus, and then proceed with selecting your desired text.

We're looking into a fix for this as we speak.

If its something else you're experiencing, please let me know and we'll do our best to provide a solution ASAP.

Thanks!

**Comment by davidbdyer** [comment]
Seems to be fixed, thank you!

**Comment by mack-at-pieces** [comment]
Thanks @davidbdyer we'll have some further enhancements in a patch release this week 👍🏼

**Comment by mack-at-pieces** [comment]
@davidbdyer last week we released updates for Pieces OS, Pieces Desktop App, & some of our plugins that includes fixes to text selection. Please let us know if you are still running into any issues 👍🏼  Thanks!
