### ISSUE TITLE
Cannot resize or maximize piece desktop app

### ISSUE THREAD

**Issue by E-m-i-n-e-n-c-e** [pieces-app/support#387]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Cannot Resize or maximize pieces desktop app

edit:
   The issue got fixed.Is there anyway to close this thread or smn.idk

**Comment by mack-at-pieces** [comment]
Thanks @E-m-i-n-e-n-c-e ! Please let us know if you run into any other issues. Closing this issue 👍🏼
