### ISSUE TITLE
'Finish Onboarding' button stuck

### ISSUE THREAD

**Issue by jaxrowe** [pieces-app/support#393]
### Software

Desktop Application

### Operating System / Platform

Linux

### Your Pieces OS Version

10.1.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi, the 'Finish Onboarding' button on the last page of the initial setup isin't doing anything. I see the ui animation trigger, just nothing happens. Ubuntu Cinnamon 24.04. I saw the same issue in a post on the discord server in 2023, was no resolution.

- Tried restarting/re-install, terminal isin't saying anything. 
- Tried giving full permissions to user.  
- Tried running pieces os and application as root, said '/run/user/0’: Permission denied', I believe that directory is for temp runtime files and decided to stop there..

It's a new install of Ubuntu with a basic pieces installation in terminal via the instructions, so a pretty default procedure overall - can't imagine something about my system configuration causing conflict. I think you have done great work here from what I can tell and I really want to give it a go, open to try any ideas you have.

**Comment by epsil0ndelta** [comment]
If it's any hint, the 'Launch Pieces OS..' on the desktop app spins forever as well - not a problem as I can launch manually, but maybe related to same issue. I have full permission given to user on the snap packages..

**Comment by epsil0ndelta** [comment]
swinging for the fences, hope you don't mind. Full disclaimer I don't really know what I'm doing x)

when I run `pieces_for_x` in `/snap/pieces-for-developers/current`, now the terminal is saying stuff.

when launched :

`flutter: [D]  ========== Application Launching: 2024-09-08 11:10:21.435868 ==========

flutter: [D]  Path to runtime_code_highlighter dynamic library: /snap/pieces-for-developers/63/lib/runtime_code_highlighter.so
flutter: RuntimeFlutterCodeHighlighter initialized with path
flutter: RuntimeFlutterCodeHighlighter initialized
flutter: [D]  Successfully initialized RuntimeFlutterCodeHighlighter
flutter: [D]  Attempting to get Pieces OS Identity File(s) - Desktop App
flutter: [D]  Attempting to get Pieces OS Identity File - Desktop App - Grabbing Segments
flutter: [D]  Successfully found Pieces OS Identity File within Desktop App: 69bc725c-7556-4763-8021-8e0d0cb9a882
flutter: [D]  Global Action Data - Initializing
flutter: [D]  Global Action Data - Initialized
flutter: [D]  Updating Arguments: []
flutter: [D]  Deployment Information: {number: 147, tag: 3.1.5, branch: 147, sha1: af83d90e55cae4035cc0c4acf3df9a90844ad9b4, winDeploymentType: null, channel: production}
flutter: [D]  Initializing sentry flutter
flutter: [D]  Booting App
flutter: [D]  Initializing Database
flutter: [D]  Stored Window Config: {size: {height: 878.0, width: 1044.0}, minSize: {height: 568.0, width: 320.0}, maxSize: {height: 2000.0, width: 2000.0}, position: {dx: 2918.0, dy: 290.0}}
flutter: [D]  Stored App View State: AppViewStateEnum.copilot
flutter: [D]  Stored Drive Layout State: null
flutter: [D]  Stored List View Sort: Recent
flutter: [D]  Stored Carousel Sort: recent
flutter: [D]  Stored Drive Action Toolbar State: {type: basic, custom: [16393a82-6e92-4bb3-ad84-6a1d8abe7b42, ea646c31-d9de-4956-989b-ee6c514b1e4d, e26e58b1-0e8d-4b8e-8778-a97e1b56d703, 73434786-e647-4be5-b705-c3844568d5ae, 1ea30b9b-ca6f-40f6-a1aa-252caab5a627]}
flutter: [D]  Initializing Window
flutter: [D]  Connecting to Pieces OS
flutter: [D]  Failed to Confirm Connection: ApiException 400: Socket operation failed: GET /.well-known/version (Inner exception: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 43052, uri=http://127.0.0.1:5323/.well-known/version)

#0      IOClient.send (package:http/src/io_client.dart:154)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:core_openapi/api_client.dart:706)
<asynchronous suspension>
#3      WellKnownApi.getWellKnownVersion (package:core_openapi/api/well_known_api.dart:180)
<asynchronous suspension>
#4      PiecesApi.getVersionNumber (package:pieces_for_x/app/apis/pieces_os.dart:458)
<asynchronous suspension>
#5      Compatibility.apps (package:pieces_for_x/app/classes/compatibility.dart:46)
<asynchronous suspension>
#6      Bootup._checkCompatibility (package:pieces_for_x/app/modules/bootup/utils/bootup_methods.dart:589)
<asynchronous suspension>
#7      Bootup.connect (package:pieces_for_x/app/modules/bootup/utils/bootup_methods.dart:394)
<asynchronous suspension>
#8      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:469)
<asynchronous suspension>

flutter: [D]  Sentry Error Event: 26269c97313f45a7bf3bfa29ac0db086, ApiException 400: Socket operation failed: GET /.well-known/version (Inner exception: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 43052, uri=http://127.0.0.1:5323/.well-known/version)

#0      IOClient.send (package:http/src/io_client.dart:154)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:core_openapi/api_client.dart:706)
<asynchronous suspension>
#3      WellKnownApi.getWellKnownVersion (package:core_openapi/api/well_known_api.dart:180)
<asynchronous suspension>
#4      PiecesApi.getVersionNumber (package:pieces_for_x/app/apis/pieces_os.dart:458)
<asynchronous suspension>
#5      Compatibility.apps (package:pieces_for_x/app/classes/compatibility.dart:46)
<asynchronous suspension>
#6      Bootup._checkCompatibility (package:pieces_for_x/app/modules/bootup/utils/bootup_methods.dart:589)
<asynchronous suspension>
#7      Bootup.connect (package:pieces_for_x/app/modules/bootup/utils/bootup_methods.dart:394)
<asynchronous suspension>
#8      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:469)
<asynchronous suspension>`

when I clicked `Launch Pieces OS` and it spins forever :

`flutter: [D]  Sentry Error Event: 1868a470fd634e3787077abe76a2c36d, ProcessException: No such file or directory
  Command: powershell.exe Start-Process  "pieces://launch"`
  
powershell.exe? isin't this linux? also the `Device Info` section of the application when it is unable to connect to pieces OS says `Min Support : Windows 10 Build 1903`.
  
when I launch Pieces OS manually after, the desktop application terminates and restarts - and I lose the terminal output to try and see what it says on the Finish Onboarding step.

**Comment by nathan-courtney-pieces** [comment]
We are aware of Pieces OS having issues on Ubuntu 24.04 and are currently investigating this

**Comment by mack-at-pieces** [comment]
Hey @jaxrowe we've released a good amount of updates since September, including a new onboarding experience for the Desktop App. Would you be willing to update or install the latest and try again? Please let us know if you are still running into issues.

**Comment by jaxrowe** [comment]
> Hey @jaxrowe we've released a good amount of updates since September, including a new onboarding experience for the Desktop App. Would you be willing to update or install the latest and try again? Please let us know if you are still running into issues.

Yes I will try again, (also curious if the vscode plugin will work with Cursor which is a vscode fork) that would be a gnarly setup. I got alot on deck atm, but I have it noted in the to do queue. Might take me like 3 weeks or somthing to get to it tho

**Comment by jaxrowe** [comment]
yep all good now, can close ticket
