### ISSUE TITLE
By activating this, my Pieces OS broke and doesn't work anymore, it automatically closes some seconds after I open. when I delete "com.pieces.os" and "com.pieces.pfd" resets Pieces OS and works fine until I turn that option on

### ISSUE THREAD

**Issue by leandroviegas** [pieces-app/support#403]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.6

### Early Access Program

- [x] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

By activating worksteam Pattern Engine, my Pieces OS broke and doesn't work anymore, it automatically closes some seconds after I open. when I delete "com.pieces.os" resets Pieces OS and works fine until I turn that option on. 
ps: It might be related by me having a bad gpu(rx550).

**Comment by mark-at-pieces** [comment]
@leandroviegas very sorry that the WPE is breaking your Pieces OS. would you have a spare minute to hop on a call w/ @brian-pieces and my self? if so here is a link to my calendar.

https://calendar.app.google/y4Qv6FRwGNmT1uT68

**Comment by leandroviegas** [comment]
> @leandroviegas very sorry that the WPE is breaking your Pieces OS. would you have a spare minute to hop on a call w/ @brian-pieces and my self? if so here is a link to my calendar.
> 
> https://calendar.app.google/y4Qv6FRwGNmT1uT68

ok, I booked on the calendar

**Comment by leandroviegas** [comment]
> @leandroviegas if you would be able to provide me w/ the logs and send to [mark@pieces.app](mailto:mark@pieces.app) this would also be very helpful.
> 
> can find the logs in com.pieces.os/production/support

I opened the program and activated the option and this is the log of everything.

[D]  2024-09-18T23:05:23.446458  Starting OS_Server!
[D]  2024-09-18T23:05:23.446458  Starting EnvConf
[D]  2024-09-18T23:05:23.446458  Starting DeploymentInfo
[D]  2024-09-18T23:05:23.447472  Number: 127
[D]  2024-09-18T23:05:23.447472  Tag: 10.1.8
[D]  2024-09-18T23:05:23.447472  Branch: 10.1.8
[D]  2024-09-18T23:05:23.447472  SHA1: 12f042c98975ceb2c424c618b0c4b091c7335b3b
[D]  2024-09-18T23:05:23.447472  WinDeployType: msix
[D]  2024-09-18T23:05:23.447472  Channel : production
[D]  2024-09-18T23:05:23.447472  Process ID: 12232
[D]  2024-09-18T23:05:23.447472  Copying the vocab file to the data directory
[D]  2024-09-18T23:05:23.447472  Successfully copied the vocab file
[D]  2024-09-18T23:05:23.447472  Starting OS
[D]  2024-09-18T23:05:23.448459  Starting OS
[D]  2024-09-18T23:05:23.449497  Starting UI
[D]  2024-09-18T23:05:23.451006  UI#builder, hasData: false, hasError: false
[D]  2024-09-18T23:05:23.452036  stateStream#onListen
[D]  2024-09-18T23:05:23.452036  OS#boot
[D]  2024-09-18T23:05:23.452036  OS#attach
[D]  2024-09-18T23:05:23.841059  Logging to file: C:\Users\Leandr\Documents\com.pieces.os\production\Support/logs/log-09182024.txt
[D]  2024-09-18T23:05:23.875301  User added tagify files now exist.
[D]  2024-09-18T23:05:23.882837  OS#attempt to shutdown qdrant
[D]  2024-09-18T23:05:24.394314  OS#successfully shutdown qdrant
[D]  2024-09-18T23:05:24.418891  OS#onBooted
[D]  2024-09-18T23:05:24.418891  OS#port: 1000
[D]  2024-09-18T23:05:24.419889  OS#totalTime: 970392
[D]  Setting WinToast Dismissed Callback
[D]  2024-09-18T23:05:24.429439  UI#builder, hasData: true, hasError: false
[D]  2024-09-18T23:05:24.445521  0:00:00.001645 GET     [200] /.well-known/health
[D]  2024-09-18T23:05:27.395473  OS#attempt to boot qdrant
[D]  2024-09-18T23:05:30.408151  OS#successfully booted qdrant
[D]  Sentry Error Event: 3b583a59ef7346439ac4ae342f10cb47
[D]  Sentry Error Event: a49b111b76224f3a9dc92a746b7f4580
[D]  Sentry Error Event: 423c19bf8e7649848cded1b5a0698a78
[D]  2024-09-18T23:05:37.929651  0:00:00.000254 GET     [200] /.well-known/version
[D]  2024-09-18T23:05:37.941065  0:00:00.000278 GET     [200] /os/permissions
[D]  2024-09-18T23:05:37.941065  0:00:00.003249 POST    [200] /connect
[D]  [34m MsixUpdaterApi: Attempting to check for an updates [0m
[D]  2024-09-18T23:05:38.106883  0:00:00.000475 GET     [200] /user
[D]  2024-09-18T23:05:38.108886  0:00:00.000245 GET     [200] /.well-known/version
[D]  2024-09-18T23:05:38.109666  0:00:00.000863 GET     [200] /workstream_pattern_engine/processors/vision/status
[D]  2024-09-18T23:05:38.111223  0:00:00.000165 GET     [200] /os/settings
[D]  2024-09-18T23:05:38.112254  0:00:00.000257 GET     [200] /workstream_pattern_engine/processors/vision/status
[D]  [34m MsixUpdaterApi: No Updates Available [0m
[D]  [34m MsixUpdaterApi: Attempting to check for an updates [0m
[D]  2024-09-18T23:05:43.534357  0:00:00.000234 GET     [200] /os/permissions
[D]  2024-09-18T23:05:43.539357  0:00:00.000716 POST    [200] /workstream_pattern_engine/processors/vision/activate
[D]  2024-09-18T23:05:43.549585  0:00:00.000369 GET     [200] /workstream_pattern_engine/processors/vision/status
[D]  2024-09-18T23:05:43.551163  0:00:00.000747 POST    [200] /7eca2bbd-c9c8-4cae-90a9-439e3d33899c/track
[D]  2024-09-18T23:05:44.116426  OS#machine learning models loaded successfully
[D]  2024-09-18T23:05:48.001065  0:00:00.000494 GET     [200] /os/permissions
[D]  2024-09-18T23:05:48.005192  0:00:00.000304 GET     [200] /workstream_pattern_engine/processors/vision/status

**Comment by mark-at-pieces** [comment]
This is now release in 10.1.9
