### ISSUE TITLE
Can't reset pieces logs location

### ISSUE THREAD

**Issue by bodzebod** [pieces-app/support#404]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi, I used a USB drive with my work laptop when I installed pieces, and my user's home folder was on it. Today, my company deployed a policy that turns any USB device as read-only. Since then, pieces desktop was unable to show any UI, despite the fact I was seeing it keeping on restarting in the task manager. I figured out that it was trying to write some logs and files (.os, database.hive, database.lock) on my readonly USB drive, under a folder D:\OneDrive\Documents\com.pieces.pfd\production\ . As a workaround, I have created a dummy D: drive with the command SUBST that maps a local folder to a drive letter. But I couldn't find where to reset this path in pieces settings. Uninstall/reinstall didn't help. Please can you guide me? Thank you!

**Comment by bodzebod** [comment]
Since I opened this ticket, I rebooted. I've just found that Pieces OS is crashing a few seconds after it starts.

**Comment by bodzebod** [comment]
I found the folder com.pieces.os I needed to copy to my dummy D: folder. After copying it, Pieces OS could start.

**Comment by mark-at-pieces** [comment]
@bodzebod very interesting issue, thank you for sending all this information over.

looks to be a few issues going on and would love to spedn some time to get you up and running as well as help answer all your questions.

Here is a link to my calendar if you have a spare 30 min!

https://calendar.app.google/y4Qv6FRwGNmT1uT68

**Comment by bodzebod** [comment]
Hi @mark-at-pieces , I have reserved a slot on next wednesday, thanks.

**Comment by bodzebod** [comment]
As seen during our support session, looks like a recent update fixed my issue, and pieces is no longer trying to write on D: drive. Thank you for your support!
