### ISSUE TITLE
Quit button in PiecesOS dropdown not working 

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#406]
Users have let us know that the "quit" button on the PiecesOS dropdown is not working. We are working on a fix, please keep an eye out on this ticket for updates!

**Comment by mack-at-pieces** [comment]
This is going to be hotfixed via a release to Pieces OS, and was addressed here: https://github.com/pieces-app/os_server/pull/1154

**Comment by rosie-at-pieces** [comment]
We have released a patch that should take care of this issue! Please update to Pieces OS 10.1.8.

If you are still experiencing this issue please let us know!
