### ISSUE TITLE
Unable to generate personal link

### ISSUE THREAD

**Issue by tombinga** [pieces-app/support#407]
### Software

Desktop Application, Pieces OS, Web Extension, VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.8

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Whenever I try to generate a shareable link, I get a "Failed to Generate Personal Link" message. I first reported this in June as part of a [previous issue](https://github.com/pieces-app/support/issues/266#issue-2370119489), and I still haven't been able to use this feature again.

![image](https://github.com/user-attachments/assets/5fbbd94b-c098-4a7d-b00a-f09daf25f16a)

**Comment by rosie-at-pieces** [comment]
duplicate #414

**Comment by tombinga** [comment]
@rosie-at-pieces if you re-read my initial post, I reported this back in June 2024 and I still can't generate shareable links. @mark-at-pieces helped me through the issue I was having connecting to my personal cloud via a 1-on-1 video call, but were never able to fix the shareable link issue.
