### ISSUE TITLE
Pieces extension modifying workspace settings

### ISSUE THREAD

**Issue by PriyanshuMallick** [pieces-app/support#408]
### Software

VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

v10.1.8

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The Pieces extension for Visual Studio Code is automatically modifying the `.vscode/settings.json` file in my workspace. It's adding the following settings:

```json
{
  "pieces.cloudCapabilities": "Blended",
  "pieces.telemetry": true
}
```

Even if I change or remove these settings from the workspace settings file, the extension keeps adding them back.

#### Expected Behavior
The Pieces extension should respect the user's global settings and not modify the workspace-specific settings file. If there are settings that need to be configured per workspace, the extension should provide a way to opt-in or out of those settings.

#### Environment
- Visual Studio Code version: `v1.93.1`
- Pieces extension version: `v1.18.0`

#### Steps to Reproduce
1. Open a new workspace in Visual Studio Code.
2. Install the Pieces extension.
3. Observe that the `.vscode/settings.json` file is created or modified with the settings mentioned above.
4. Change or remove the settings from the file.
5. Reload Visual Studio Code or the workspace.
6. Observe that the settings are added back to the `.vscode/settings.json` file.

#### Additional Information
I have these settings configured in my global user settings, so they don't need to be added to the workspace settings file. Additionally, I don't want these settings to be committed to version control (e.g., GitHub) as they may not be applicable or desired for all users of the project.

Please consider providing a way to disable this behavior or make it an opt-in feature for workspaces that require these settings.

**Comment by mack-at-pieces** [comment]
Hi @PriyanshuMallick - Thanks for bringing this to our attention. The team will be looking into this and will hopefully have a resolution within the next few days 👍🏼
