### ISSUE TITLE
Hotkey CTRL+ARROW KEYS not working

### ISSUE THREAD

**Issue by xXTurnerLP** [pieces-app/support#409]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.6

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When you want to move the typing cursor left or right by skipping whole words (CTRL+LEFT ARROW or CTRL+RIGHT ARROW) it does not work in the "Copilot Chats" window. A workaround is to press CTRL+SHIFT+LEFT ARROW or CTRL+SHIFT+RIGHT ARROW but this will select the text and you need to press one of the arrow keys to remove the selection

**Comment by mack-at-pieces** [comment]
Hi @xXTurnerLP - Have you had a chance to update to the latest version of Pieces OS & the Desktop Application? This should be updated with the latest versions.

If it's not, please let us know!

Thanks!
