### ISSUE TITLE
Nested webpages through contact form

### ISSUE THREAD

**Issue by SaltySpaghetti** [pieces-app/support#411]
### Software

Marketing Site (pieces.app)

### Operating System / Platform

Web

### Your Pieces OS Version

None

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Every time you fill the contact form on the website, when you have finished to fill it a “Back to home” button gets displayed. Clicking it creates a nested website inside the pre-existing one

https://github.com/user-attachments/assets/1c53c119-f30c-4185-b007-2489a791761a

**Comment by rosie-at-pieces** [comment]
@SaltySpaghetti we migrated our website to a new design late last week; this may be resolved now. I could not get this issue to reproduce, can you please check and see if you are still experiencing it?

**Comment by SaltySpaghetti** [comment]
The "Back home" button is gone, so it seems that the bug can't be reproduced anymore.
