### ISSUE TITLE
Brew doesn't install piecesOS

### ISSUE THREAD

**Issue by hra42** [pieces-app/support#424]
### Software

Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

n/v

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

==> Downloading https://builds.pieces.app/stages/production/pieces_for_x/macos-arm64/
==> Downloading from https://storage.googleapis.com/app-releases-production/pieces_fo
############################################################################## 100.0%
Warning: No checksum defined for cask 'pieces', skipping verification.
All dependencies satisfied.
==> Installing Cask pieces
==> Moving App 'Pieces.app' to '/Applications/Pieces.app'
🍺  pieces was successfully installed!

**Comment by nathan-courtney-pieces** [comment]
@hra42 

Were you able to get Pieces OS installed? 

The cask file for Pieces for Developers depends on Pieces OS. Are you saying it did not get installed with it? You weren't prompted or anything?

**Comment by hra42** [comment]
@nathan-courtney-pieces yes I installed it manually without brew. 

I retried it now and now the dependency of pOS gets installed correctly.
