### ISSUE TITLE
Unable to Activate Workstream Pattern Engine - "Paused Until" Keeps Increasing

### ISSUE THREAD

**Issue by imkrishnasarathi** [pieces-app/support#426]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

v10.1.9

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I am facing an issue with the Workstream Pattern Engine in Pieces. Every time I try to turn it on, the status displays "Paused until X", and each attempt to enable it results in the "Paused until" value increasing. As a result, I am unable to use the Live Context feature.

**Steps to Reproduce:**

- Open the Pieces application.
- Navigate to the Workstream Pattern Engine settings.
- Attempt to turn it on.
- Observe the "Paused until X" message and how the value changes with each attempt.'

**Expected Behavior:**
The engine should turn on immediately upon activation, allowing access to the Live Context feature.

**Comment by elliezub** [comment]
Hey @mack-at-pieces @mark-at-pieces, looks like Krishna is having some issues with the Workstream Pattern Engine not functioning as expected

**Comment by tsavo-at-pieces** [comment]
Hey there @imkrishnasarathi would love to try and help you solve this! Could you grab time on the support calendar so we can troubleshoot live? 

https://calendar.app.google/MKeJdRP8US4Z8C1Y6

**Comment by tsavo-at-pieces** [comment]
@nathan-courtney-pieces for visibility here.

**Comment by imkrishnasarathi** [comment]
Thank you @tsavo-at-pieces !! :) Really Appreciate the help! 😃

**Comment by mark-at-pieces** [comment]
will be resolved in the next PiecesOS release

https://github.com/pieces-app/os_server/issues/1246

10.1.11

Thanks you for raising this issue!
