### ISSUE TITLE
Pieces OS crashes after upgraded to 10.9.1

### ISSUE THREAD

**Issue by gonzososa** [pieces-app/support#430]
### Software

Pieces OS

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.10

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

After upgrade Pieces OS to 10.1.9 it started to crash every time. Tried reinstall that version but failure remains, then upgrade to version 10.1.10 but the issue is still happen. 

Attached is a fragment of crash log report.

thanks for your help.

[crash_log.txt](https://github.com/user-attachments/files/17437582/crash_log.txt)

**Comment by sam-at-pieces** [comment]
Thank you for raising this issue @gonzososa, that must be very frustrating! @mack-at-pieces @brian-pieces, from the logs this looks like it could be a llamacpp dylib issue or an issue with rendering in flutter, what do you think?

**Comment by mack-at-pieces** [comment]
@sam-at-pieces Could be one or the other, or both. @gonzososa thanks for sharing this issue. Can you please share some additional information to help us debug.

1. What is your macOS version?
2. There are log files located at `User/{user}/Library/com.pieces.os/production/Support/logs` - can you please share the most recent one for a day you experienced the crash?

Thanks so much.

**Comment by gonzososa** [comment]
Hey @mack-at-pieces sure, here it is.

OS Version: MacOS Ventura 13.6.9 (22G830)

Cheers.

[log-10192024.txt](https://github.com/user-attachments/files/17446646/log-10192024.txt)
[log-10172024.txt](https://github.com/user-attachments/files/17446647/log-10172024.txt)
[log-10162024.txt](https://github.com/user-attachments/files/17446648/log-10162024.txt)
[log-10152024.txt](https://github.com/user-attachments/files/17446649/log-10152024.txt)

**Comment by mark-at-pieces** [comment]
Hey @gonzososa would you be willing to chat in realtime? We are not 100% sure the cause of this issue(and are unable to reproduce) however we have a few Ideas.

Here is a link to my calendar: https://calendar.app.google/Xo2kHrXMduE3xiDU6

We would be super grateful and toss you a gift card or some merch from the Pieces Store.

Looking forward to hearing from you!

**Comment by gonzososa** [comment]
Hey Mark thanks for you support and sorry for late response. As it seems it’s a concern of my system only I’m gonna upgrade entire OS to next major version. Come back to you if that doesn’t solve the problem.

Cheers.


GS

**Comment by gonzososa** [comment]
Hello there, just to let you know that the issue has been resolved. As I said I upgraded OS and although it doesn't fix the problem (pieces-os continued to crash) eventually an update appears and after upgrade  it to version 10.1.11 everthing is working well.


Best regards.

**Comment by tsavo-at-pieces** [comment]
Hey there! @gonzososa amazing to hear. We just pushed out another critical release see #444 - try that one out and let us know how it goes for you 🤝

**Comment by gonzososa** [comment]
Upgraded to version 10.1.12 and everything is working well..Thanks.


Regards.
