### ISSUE TITLE
Pieces-OS not running on Ubuntu server 22.04

### ISSUE THREAD

**Issue by mack-at-pieces** [pieces-app/support#434]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Linux

### Your Pieces OS Version

10.1.10

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

As the title says, Pieces-OS is not running on a machine I have installed Ubuntu Server 22.04. I have OpenAIs Whisper installed on this machine as well and intend to use for other Machine Learning exercises. However when I try to run Pieces-OS it completes and does nothing. I have checked to see if it is listening on a port or if there is an issue with the firewall and I see nothing. ufw is returning status of Inactive, and I don't see anything listening on port 5323 or anything in the 5000 range. I have checked under /var/log and do not see any logs there to share to try and help on this issue. I do not have any kind of UI installed on the server in case that matters. Any guidance on where to look for error messages would be appreciated.

Original Post: https://www.reddit.com/r/PiecesForDevelopers/comments/1g0rshy/piecesos_not_running_on_ubuntu_server_2204/?share_id=XSXHdDTjEZ5Mt_E3L9Bbl&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1

Original User:
https://www.reddit.com/user/catrone3/

**Comment by catrone3** [comment]
Thanks for creating the issue on this, wasn't going to make one if it was something the community new the answer to.

**Comment by mack-at-pieces** [comment]
No problem. Thanks for bringing it to our attention @catrone3. @nathan-courtney-pieces do you mind taking a look here?

**Comment by hra42** [comment]
As far as I'm aware piecesOS needs some UI components to work properly, so if you don't have a gui it's expected that it's not working.

@mack-at-pieces maybe you can provide more details if that's still the case.

**Comment by tsavo-at-pieces** [comment]
This may work now with the new headless mode.

**Comment by catrone3** [comment]
is that released now or is it still in testing?

**Comment by catrone3** [comment]
That appears to have worked, not the most elegant solution but I will take a working solution. Thank you.

**Comment by rosie-at-pieces** [comment]
Thanks for bearing with us while we work out a better solution for this @catrone3 !
