### ISSUE TITLE
Pieces Suite Installer ~ Installation Progress Finicky On Slower Internet Connections

### ISSUE THREAD

**Issue by nathan-courtney-pieces** [pieces-app/support#44]
### Software

Pieces OS

### Operating System

Windows

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Some users have reported that with a slower internet connection, the installation progress is not displayed properly, or doesn't display at all.

**Comment by rosie-at-pieces** [comment]
If you are still experiencing this please comment on this issue, the team is continuously improving the installation process.
