### ISSUE TITLE
I'm sorry. Somethign went wrong with processing

### ISSUE THREAD

**Issue by raayraay96** [pieces-app/support#440]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

Pieces OS 10.1.11

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Not sure but it just keeps doing this and i reset it, turn app off and on. Hit the hard reset on chat feature and it still not working.
![Screenshot 2024-11-04 104328](https://github.com/user-attachments/assets/4bd8d231-9df6-44ae-bc7e-e49bfb56e2d9)

**Comment by rosie-at-pieces** [comment]
Hi there, so sorry about this! Here's some troubleshooting for all users when they experience this:

1. Are you entirely up to date with PiecesOS and the Pieces Desktop App and/or whatever plugin you are using the copilot in? 
2. If using a cloud LLM: please check your internet connection, and if you are running a firewall please ensure that you are allowing PiecesOS. There is a small chance that the cloud model you are using is experiencing an issue, it is always good to try multiple to see if any are working.
3. If using a local LLM: local models can overwhelm your computer's resources dependent on the type of machine you have. The Microsoft Phi models are generally the most resource friendly, but local models typically work best on newer (2021 and later) machines with a dedicated GPU.
4. If using your own OpenAI API key, please check your quota and rate limits; you may have hit your limit.
5. Did you add context to the copilot? If so, try removing it and see if that works. If so, you can send us detail about this so we can better advise.

Let me know if any of this helps or if you're still experiencing this!

**Comment by tsavo-at-pieces** [comment]
Related to #445 and #444 and #441

**Comment by tsavo-at-pieces** [comment]
We're working on it asap! A couple of updates have gone out both in the cloud and with all of the products. 

If you could update your Pieces OS & Desktop App/Any Plugins and send screenshots of what you get back after the fact that would be tremendously appreciated @raayraay96 !

**Comment by mark-at-pieces** [comment]
@raayraay96 just checking in, if you upgrade to the latest version of PiecesOS 10.1.12 is this issue resolved?

**Comment by raayraay96** [comment]
Ya i think its good sometimes there is issues but just reset app and lym works again

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mark Widman ***@***.***>
Sent: Monday, November 11, 2024 9:04:39 AM
To: pieces-app/support ***@***.***>
Cc: Raymond, Eric Davon ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [pieces-app/support] I'm sorry. Somethign went wrong with processing (Issue #440)


This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@raayraay96<https://github.com/raayraay96> just checking in, if you upgrade to the latest version of PiecesOS 10.1.12 is this issue resolved?

**Comment by rosie-at-pieces** [comment]
Closing this as this issue is resolved, if you are still experiencing issues please refer to https://github.com/pieces-app/support/issues/445
