### ISSUE TITLE
Adding Snippets into Copilot Context leads to minor bug

### ISSUE THREAD

**Issue by seantiz** [pieces-app/support#45]
### Software

Desktop Application

### Operating System

macOS

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi there,
<img width="1061" alt="Screenshot 2024-01-17 at 02 52 48" src="https://github.com/pieces-app/support/assets/135666428/5a3dcb1a-a2d6-48b8-b750-a1337cc6f7be">

When create a New Conversation in Copilot on Pieces Desktop, I click on the Manage Conversation icon to the bottom left by the Text input field, and click on Add Snippets. I select some Snippets and then press Done.

From this point onwards: the Text input field is unusable. It doesn't change appearance, but clicking on it to input text has no effect and it's not possible to type anything into the field.

This is a minor bug for now, if I click on another conversation and then return to my newly-created conversation, the text field works as intended again.

**Comment by mack-at-pieces** [comment]
Hey @seantiz Thanks so much for bringing this to our attention. We're going to get that patched up ASAP! We'll update this issue as progress unfolds 👍🏼

**Comment by mack-at-pieces** [comment]
Update: The problem has been identified and addressed. This will be released with the next Desktop App release, scheduled for the week of January 21, 2024.
