### ISSUE TITLE
PROXY CONNECTION ISSUE

### ISSUE THREAD

**Issue by DANIELMWENDWA9451** [pieces-app/support#450]
### Software

Pieces OS

### Operating System / Platform

Linux

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I hereby request you implement a feature in the Pieces OS to allow Proxy configuration and access in the copilot chats since some of use use internet from Proxy servers.Thanks you.

**Comment by rosie-at-pieces** [comment]
hi @DANIELMWENDWA9451 this is a great idea! will you please post this as an Idea on our [discussions](https://github.com/pieces-app/support/discussions)? i've added an internal ticket for this as well which i'll attach to the discussion.

**Comment by DANIELMWENDWA9451** [comment]
I did so.Thanks
