### ISSUE TITLE
Cannot view conversation messages when index is 1 (the only conversation available)

### ISSUE THREAD

**Issue by buzby08** [pieces-app/support#452]
### Software

Pieces CLI

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I have one conversation in pieces. I can see this conversation in the Pieces for Developers app. In the CLI, i list all the conversations. It shows one conversation, named JARVIS, written as `1. JARVIS`. I would assume that this means the index of the chat is `1`. If i try the command `pieces conversation 1` to view the conversation messages, i get a **python** error saying list index out of range. As a python programmer, i looked at the code, and then tried to run the command `pieces conversation 0`, in case the index is not shown correctly. This raises a pieces error saying the conversation is empty. The conversation has one message from me, and one response from the LLM. This has been confirmed from Pieces for developers app. I have provided pictures to aid. 

![image](https://github.com/user-attachments/assets/0195977f-c5c1-44ad-9977-165c8eed2bd5)
![image](https://github.com/user-attachments/assets/1ea9d812-4547-4c2e-93f0-36783261de2c)

**Comment by Bishoy-at-pieces** [comment]
Hello @buzby08 ,
Thank you for bringing this to our attention. It should be resolved in the latest version. You can upgrade to the latest version by running the following command:
```cmd
pip install pieces-cli --upgrade
```
Make sure you are on version 1.8.2
```cmd
pieces -v
```
