### ISSUE TITLE
Pieces unable to extract useful information from context

### ISSUE THREAD

**Issue by kristofmulier** [pieces-app/support#454]
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

We integrated Pieces into Embeetle IDE through the pieces-os-client Python SDK. When the user starts a project and launches a conversation with Pieces, we provide the codefiles to Pieces. However, Pieces seems unable to extract useful information from these codefiles.

I've raised an issue for that in here (with more detailed information):
https://github.com/pieces-app/pieces-os-client-sdk-for-python/issues/99

@Bishoy-at-pieces adviced me to also report it here in the support repo. As of today, the context filtering doesn't work properly, so our claim that Embeetle IDE integrated Pieces to provide "context-aware coding help" isn't living up to expectations. That is a real problem for us.

**Comment by tsavo-at-pieces** [comment]
@sam-at-pieces @pieceskieran Can the two of you comment & jump in here. @mark-at-pieces will want your eyes on this as well!

**Comment by kristofmulier** [comment]
It works now, since version 4.0.4 of `pieces_os_client`:

![image](https://github.com/user-attachments/assets/3e91b09b-243a-4c54-8b28-1f00c8bdb6c6)

Thank you guys!
