### ISSUE TITLE
Pieces Backups never finish loading

### ISSUE THREAD

**Issue by hra42** [pieces-app/support#467]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

If you have a fresh pieces Cloud account, the fetching of backups never finish.
![Image](https://github.com/user-attachments/assets/af5dbb5e-102a-46b9-9165-4372ec4a2578)

It seem that this prevents you from creating a backup
![Image](https://github.com/user-attachments/assets/db0da8e3-9416-4ec6-a9ab-0b358af87d98)

My personal cloud account is connected:
![Image](https://github.com/user-attachments/assets/f2a5c463-cb47-47ae-bef8-0a1a40d70244)

Once I restarted pieces after I first opened the backup section is seems to work and find older backups:
![Image](https://github.com/user-attachments/assets/e9f53f6f-9286-4f73-b327-21ac3930975e)

Logs:
PfD:
[log-11202024.txt](https://github.com/user-attachments/files/17835166/log-11202024.txt)
pOS:
[log-11202024.txt](https://github.com/user-attachments/files/17835170/log-11202024.txt)

**Comment by mark-at-pieces** [comment]
@hra42 Thank you so much for bringing this up to our attention, I have seen this issue before 100%, but it has been tricky for me to reproduce, however we have pushed a few changes around the cloud feature w/ 10.1.13 just last evening so I would strongly reccomend checking it out.

That being said we are in development on a major upgrade to all things cloud featurues that will replace everything that we know in production today(will land around End of December of early January at the latest) so stay tuned.

**Comment by hra42** [comment]
thank you so much @mark-at-pieces, from my pov we could close the issue for now and monitor if we get more reports after the update you mentioned.
