### ISSUE TITLE
pieces os install issues [just testing]

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/support#468]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

this is just for testing but pieces os wont install.... etc,

**Comment by mason-at-pieces** [comment]
#127

**Comment by mark-at-pieces** [comment]
@mason-at-pieces we can close this correct?
