### ISSUE TITLE
Catastropic forgetting in the Generalized Code Chat dialogue

### ISSUE THREAD

**Issue by sam-at-pieces** [pieces-app/support#473]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The context is forgotten between messages unless they are all added to the memory manually.

**Comment by sam-at-pieces** [comment]
Hi Sam,


I hope this is helpful. This is a conversation I had with Claude through Pieces Desktop this morning. It is no longer than 5 queries on my side (and 5 responses). By the fifth query, Claude feels unable to answer because the question I'm asking is seen as out of context.

This may or may not be intended behaviour from your point of view.

The conversation began with me asking: “what is the fundamental underlying structure of a Javascript object in the stack frame?”

How it ends is in the image attached.

Sean.

![Image](https://github.com/user-attachments/assets/97a262bb-c5f2-4fd2-9733-0b177587a9be)

**Comment by sam-at-pieces** [comment]
Hi Sean,
Thanks a lot for this, I really appreciate you communicating the issue. So, to summarize:
You are referring back to ideas/concepts that were mentioned 5 messages previously and the copilot is having trouble recognizing them. This is particularly an issue on Claude. Do you have any context added to the conversation at all?
I'd be very interested to know if you have similar issues with other models. The issue here could well be the underlying model context size so it would be really useful to know if the problem persists with gpt40 or gemini pro.
I will set up an issue when I'm back in front of my laptop, add the above and link you so I can easily pass on details to other people on the team.
Best wishes,
Sam

**Comment by sam-at-pieces** [comment]
Hi Sam,

Sure I’ll happily post the feedback in an issue, just give me a tag or an email when it’s open.

For now to answer your follow-up questions:

1. Just to clarify on my end: I was NOT referring to the initial idea/concept in my opening question of the conversation. 

The first four questions and last (fifth) question are widely related (in the sense that my fifth question was about creating objects/methods and that does push new call stack frames) but what I’m getting at is that Claude (through Pieces) doesn’t allow for that wide of a natural train of thought right now.

So (in my opinion) it has trouble follow natural conversation, it narrows in on pre-existing conversation context in very little time and sticks rigidly to that scope. The side effect of this is opening many new conversations in Pieces Desktop now 😄

2. No context added to that conversation - neither at the start nor any time after.

3. I haven’t used the other models but I will do.

Best wishes,

**Comment by sam-at-pieces** [comment]
This should be resolved with Kieran's patch to the Generalized Code chat pipeline

**Comment by sam-at-pieces** [comment]
You are correct @seantiz ! That's how we refer to the copilot when there is no context attached

**Comment by mark-at-pieces** [comment]
going to be release in 10.1.15, going to close this issue, please reopen if this is not resolved in 10.1.15

related to https://github.com/pieces-app/os_server/issues/1362
