### ISSUE TITLE
Unhandled Exception and Processing Errors in Pieces OS and Visual Studio Extension

### ISSUE THREAD

**Issue by rohanrathi99** [pieces-app/support#478]
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I recently installed Pieces OS and Pieces Desktop using the Pieces Installer and also added the Visual Studio extension. I carefully followed all the steps outlined in the installation guide and restarted my system three times.

After completing the installation:

1. I logged into Pieces OS using my credentials.
2. Upon attempting to open the Desktop application, I encountered an Unhandled Exception error with an option to contact support.
3. Similarly, the extension in Visual Studio is not functioning. It shows the error:
"I'm sorry. Something went wrong with processing. Please wait a few seconds and try again, or contact support@pieces.app."

Despite multiple attempts, I have been unable to resolve the issue. Could you please provide guidance on fixing this? If the issue persists, I may need to remove the software from my system.

Looking forward to your assistance.

**Comment by mack-at-pieces** [comment]
Hey @rohanrathi99 - Thank you for sharing this issue, and so sorry you're running into problems. Hopefully we can help fix.

Unfortunately, I wasn't able to immediately reproduce this issue, but it would be helpful to gather a few things from you.
1. Please share a screenshot of the Desktop app screen you're experiencing.
2. A set of log files is located at the path "C:\\Users\<user>\Documents\com.pieces.pfd\production\logs". Could you please share the latest one with me? This will hopefully provide more information about the error you're experiencing.
3. Yesterday afternoon we deployed a patch to our Visual Studio extension. Can you please make sure you're up-to-date with the latest extension and try again?

If it's easier to troubleshoot live, feel free to book a time to connect with me that's convenient for you via my calendar link: https://calendar.app.google/4c7hZEtghdnuTAgc6

Thanks!

**Comment by rohanrathi99** [comment]
Thank you for your response and assistance.

I followed your suggestion and performed a complete reinstallation of the Pieces application. However, I encountered a recurring issue during the startup process. After reinstalling, starting both Pieces OS and the desktop application required me to restart my system two or three times. On the third attempt, I received a Windows Defender error indicating the process was blocked.

To resolve this, I temporarily disabled Windows Defender, which allowed the application to start successfully.

Could you please let me know if there’s a way to run Pieces without needing to disable Windows Defender? Any additional guidance or steps would be greatly appreciated.

Thank you for your support!

**Comment by rohanrathi99** [comment]
Thank you for your quick response and assistance.

I followed your suggestion and performed a complete reinstallation of the Pieces application. However, I encountered a recurring issue during the startup process. After reinstalling, starting both Pieces OS and the desktop application required me to restart my system two or three times. On the third attempt, I received a Windows Defender error indicating the process was blocked.

To resolve this, I temporarily disabled Windows Defender, which allowed the application to start successfully.

Could you please let me know if there’s a way to run Pieces without needing to disable Windows Defender? Any additional guidance or steps would be greatly appreciated.

Thank you for your support!
