### ISSUE TITLE
PFD Onboarding: Context exceeded" error on first short message

### ISSUE THREAD

**Issue by claire-at-pieces** [pieces-app/support#505]
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

On first use of PFD v. 3.2.4 after completing the install wizard, I get a "Context exceeded" error with a short message to copilot in empty chat using (using default model `Claude Sonnet 3.5`) 

Repro 
1. fresh install of PDF on MacOS
2. complete wizard with defaults
3. in chat opened on load, ask default model Claude Sonnet 3.5 "Yo world"

May be related to #487 , but creating separate issue as it relates to onboarding

https://github.com/user-attachments/assets/481c3e22-5e84-436d-b81a-4f8bfdc88083

**Comment by mark-at-pieces** [comment]
hey @claire-at-pieces

Thanks for adding this ticket

This is a duplicate issue of https://github.com/pieces-app/support/issues/487

This will be resolved in the next release of PiecesOS.
