### ISSUE TITLE
Pieces for Developers app keeps crashing continuously on attempts to upload files and folder and needs restart on my windows 11 laptop

### ISSUE THREAD

**Issue by omkar-4** [pieces-app/support#507]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Pieces for Developers app keeps crashing continuously on attempts to upload files and folder and needs restart on my windows 11 laptop

**Comment by omkar-4** [comment]
query - "It would however be extremely helpful if you would be able to share some of the files/folders used w/ the Pieces Copilot."

my reply - I just uploaded my "src" file from react-vite based project and a few other folder realted to mern backend like controllers, utils etc. which contains my code files all in either .js .jsx or .md format @mark-at-pieces

**Comment by mark-at-pieces** [comment]
would you be able to zip and send me the folder? or should you send me a link to the repo?

@omkar-4

**Comment by mark-at-pieces** [comment]
linked to https://github.com/pieces-app/support/issues/536

**Comment by mark-at-pieces** [comment]
Going to close this as a duplicate for now please follow this issue for continuous updates on this issue ^^^
