### ISSUE TITLE
[Obsidian]

### ISSUE THREAD

**Issue by claire-at-pieces** [pieces-app/support#509]
### Software

Obsidian

### Operating System / Platform

macOS

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When resizing the right tray, two mysterious icons appear in upper left and lower right

Occurs in both Copilot and Snippets tabs

Confirmed this only happens when Pieces is active in the right tray, not when other plugins are active in the right tray.

https://github.com/user-attachments/assets/830457d3-4dfc-44fa-a0dc-3f50ab7ea906

Obsidian version 
1.7.7

System
```
Model Name: MacBook Pro
Model Identifier: MacBookPro18,2
Chip: Apple M1 Max
Total Number of Cores: 10 (8 performance and 2 efficiency)
Memory: 64 GB
System Firmware Version: 10151.101.3
OS Loader Version: 10151.101.3
```

**Comment by mason-at-pieces** [comment]
Hey @claire-at-pieces, so I can't see the video you posted however I think I know what you're seeing.

We have 2 icons appear in the corner of our copilot so we can identify where it is on the screen.

This is known and should appear. Let me know if that solves this for you.

**Comment by claire-at-pieces** [comment]
Thanks @mason-at-pieces
