### ISSUE TITLE
Windows Llama 7b GPU broken, CPU works

### ISSUE THREAD

**Issue by truszko1** [pieces-app/support#52]
### Software

Desktop Application, VS Code

### Operating System

Windows 11 x64

### Your Pieces OS Version

7.2.6

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I get an immediate error response from the GPU model when I try from the Desktop app or the VSCode extension.

![image](https://github.com/pieces-app/support/assets/10970127/85fa8f0b-18f5-4afe-9919-2799ce10917d)

CPU model works just fine. I tried restarting the apps, the host OS (windows), and deleting and re-downloading the GPU model.

If I send a second "test" message, after the initial error, I get this:

![image](https://github.com/pieces-app/support/assets/10970127/e8d2d995-672e-410b-b465-fdce54b49d40)

Let me know what other info you need from me.

Here are my computer specs:
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Graphics          NVIDIA GeForce RTX 3080 Laptop GPU (8GB) + Intel(R) UHD Graphics

**Comment by brian-pieces** [comment]
@truszko1 sorry to hear you're having this problem! 8GB of VRAM should be more than sufficient for the LLama2 7B model (it uses ~5.6GB) unless you have other programs running that are eating up VRAM as well.

Our system depends on the Vulkan GPU driver, so if you wouldn't mind confirming that you have it installed by running the command `vulkaninfo` in the Command Prompt that would be great. The driver should come bundled with your NVIDIA driver. 

If all this looks good, then I'm more than happy to jump on a call to dive deeper into the problem!

**Comment by truszko1** [comment]
```
C:\Users\trusz>vulkaninfo
WARNING: [Loader Message] Code 0 : Layer VK_LAYER_Twitch_Overlay uses API version 1.1 which is older than the application specified API version of 1.3. May cause issues.
ERROR: [Loader Message] Code 0 : vkCreateDevice:  Failed to create device chain.
ERROR at C:\j\msdk\build\Khronos-Tools\repo\vulkaninfo\vulkaninfo.h:1714:vkCreateDevice failed with ERROR_DEVICE_LOST
```

**Comment by truszko1** [comment]
I have the NVIDIA driver version 546.65 installed.

**Comment by brian-pieces** [comment]
As far I can can tell 546.65 is latest driver version for your machine so that should be fine. I believe what could be happening is that the Twitch Overlay software is intercepting our Vulkan API calls and the version mismatch is causing it to fail. Here's a similar [thread](https://forums.developer.nvidia.com/t/vulkan-api-deactivated/253449/3#:~:text=May%2017-,Well,-%2C%20it%20seems%20Overwolf) I found. As they say, I would unfortunately suggest uninstalling or updating that software and retesting the `vulkaninfo` command.

**Comment by truszko1** [comment]
@brian-pieces 

WOW. I uninstalled Twitch Studio, rebooted, and my Pieces GPU model works just fine now. 

I would have never thought to check `vulkaninfo`. Thank you so much!!!

**Comment by brian-pieces** [comment]
That's awesome! So glad to hear that! Never would've thought Twitch Studio would interfere with an LLM 😂 Sorry you had to uninstall that though - I hope you're able to reinstall and use it normally

**Comment by truszko1** [comment]
If that continues to be an issue, that'll be a Twitch support ticket 🙃

**Comment by truszko1** [comment]
Looks like it can affect other things too 🙃 
https://www.reddit.com/r/Doom/comments/10g5ngm/anybody_know_what_i_should_do_about_this_the_game/

**Comment by brian-pieces** [comment]
Yeah seems to be an ongoing problem, suprised they haven't patched it yet. 

Also, now that you're up an running with our GPU models, be on the lookout for a significantly higher quality 7B parameter LLM in one of our next few updates 😄

**Comment by truszko1** [comment]
> Yeah seems to be an ongoing problem, suprised they haven't patched it yet.
> 
> Also, now that you're up an running with our GPU models, be on the lookout for a significantly higher quality 7B parameter LLM in one of our next few updates 😄

which one?? 👀

**Comment by brian-pieces** [comment]
It'll be a Mistral 7B finetuned on code so it should work great with Pieces. We're testing out a different options right now to see which works best for our Copilot!

**Comment by truszko1** [comment]
oh mistral is great!! I'm using it in my privateGPT and LM Studio 😄

**Comment by brian-pieces** [comment]
Very nice, I love LM Studio! We're planning on supporting loads more models so if you have any favorites let us know and we'll add it to the list!
