### ISSUE TITLE
Can't turn on long term memory engine

### ISSUE THREAD

**Issue by sh02sahil** [pieces-app/support#526]
### Software

Desktop Application, Pieces OS, VS Code

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

i keep clicking on the button but the ltm engine wont turn on
![Image](https://github.com/user-attachments/assets/d91ee8ce-b8e1-4f28-9785-02d488d88775)

**Comment by sh02sahil** [comment]
none of these help

**Comment by mason-at-pieces** [comment]
Hey @sh02sahil, I'd love to confirm a few baseline points here before we get deeper into:
- Have you tried restarting Pieces OS and attempting to start the LTM engine?
- Are you using Pieces on Local Mode?

**Comment by sh02sahil** [comment]
Yes, I tried restarting and trying again, but it didnt work
I use pieces on local mode, but even switching to cloud mode didnt help turn on the ltm engine

**Comment by mark-at-pieces** [comment]
@sh02sahil we have seen this issue a few times in the wild:

1. we have a release out going out this evening (that might have a potential fix for you)
2. please let us know if the 11.0.0 POS breaking change will resolve your issues.(NOTE: will have a Desktop application release as well to be compatible)
3. if it fails still please schedule some time on my [calendar](https://calendar.app.google/L6qBKDnsNqSRBp7E8)

**Comment by sh02sahil** [comment]
the application can still not find the update, I'll keep you posted once the update is available for me and I've tested it

**Comment by mark-at-pieces** [comment]
Looking forward to our chat, we did have a major release today, so I might give POS 24 to try and check for updates, but more than willing to hop on a call

**Comment by sh02sahil** [comment]
Update: Just got the new 11.0.0 version, and nope, the issue still remains the same

**Comment by sh02sahil** [comment]
Update: I now can't access the vscode extension due to my wsl environment. I have tried the wsl troubleshooting steps including mirrored networking mode and adding inbound rule on my fireeall

**Comment by mark-at-pieces** [comment]
@sh02sahil I know we just got off of a call, wanted to keep everyone in the loop:

1. LTM is now fully functional
2. Context is crashing POS on windows([issue](https://github.com/pieces-app/support/issues/536))
3. Claude 3.5 sonnet is having issues in the copilot ([issue](https://github.com/pieces-app/support/issues/535))

For now, I am going to close this issue. please reopen any issues that I may have missed.

Thank you again for all your help
