### ISSUE TITLE
Access blocked: pieces.services has not completed the Google verification process

### ISSUE THREAD

**Issue by truszko1** [pieces-app/support#53]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

7.2.6

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Using the Windows Pieces Desktop app, I tried adding a Google account, but I received the `Access blocked: pieces.services has not completed the Google verification process` error.

# Step 1: clicking "Connect to Google"
![image](https://github.com/pieces-app/support/assets/10970127/bfeb7b2d-f050-4bb2-9a28-017fab69d8dd)

# Step 2: clicking "Continue with Google"
[Full URL for auth.pieces.services/u/login/identifier](https://auth.pieces.services/u/login/identifier?state=hKFo2SA2MnFuRU5sa0daYXZQd1AtZHhlcnpBS1UydjJNSjg2YqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIFl3QXl6cVB3S3o4enVxdkxoeW5EUW4zS2hDQUlWYjczo2NpZNkgM25ndEtBQVpNeGRUMTBsMTVnRkZJT2doQ2c0cWRCNkc)
![image](https://github.com/pieces-app/support/assets/10970127/3b5167af-ebaf-4ebb-8c45-0950be676ed4)

# Step 3: after choosing my Google account
[Full URL for accounts.google.com/signin/oauth](https://accounts.google.com/signin/oauth/error/v2?authError=Cg1hY2Nlc3NfZGVuaWVkEsoBVGhlIGRldmVsb3BlciBoYXNu4oCZdCBnaXZlbiB5b3UgYWNjZXNzIHRvIHRoaXMgYXBwLiBJdOKAmXMgY3VycmVudGx5IGJlaW5nIHRlc3RlZCBhbmQgaXQgaGFzbuKAmXQgYmVlbiB2ZXJpZmllZCBieSBHb29nbGUuIElmIHlvdSB0aGluayB5b3Ugc2hvdWxkIGhhdmUgYWNjZXNzLCBjb250YWN0IHRoZSBkZXZlbG9wZXIgKHRzYXZvQHBpZWNlcy5hcHApLhpEaHR0cHM6Ly9zdXBwb3J0Lmdvb2dsZS5jb20vYWNjb3VudHMvYW5zd2VyLzM0NjY1MjE_cD1hcHBfbm90dmVyaWZpZWQgkwMqFQoNcmVzcG9uc2VfdHlwZRIEY29kZSo7CgxyZWRpcmVjdF91cmkSK2h0dHBzOi8vYXV0aC5waWVjZXMuc2VydmljZXMvbG9naW4vY2FsbGJhY2sqKQoFc3RhdGUSIEgyYl8tZmlZQmVVMkdhc3Foa3RrYy1XdjlfREFybms2Kg8KBnByb21wdBIFbG9naW4qVQoJY2xpZW50X2lkEkg2NDA0ODE1MTM3NDAtdDRmNzJvZm4zbjdrb3QyMm1uNGJvcjJoanM0dGp2NDYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20qFQoLYWNjZXNzX3R5cGUSBm9ubGluZSpvCgVzY29wZRJmaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC91c2VyaW5mby5lbWFpbCBodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL3VzZXJpbmZvLnByb2ZpbGUgb3BlbmlkMooBCAQahQFodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3Byb2R1Y3Rpb24tcmVhZGluZXNzL2JyYW5kLXZlcmlmaWNhdGlvbj9obD1lbiNwcm9qZWN0cy11c2VkLWluLWRldi10ZXN0LXN0YWdl&client_id=640481513740-t4f72ofn3n7kot22mn4bor2hjs4tjv46.apps.googleusercontent.com&app_domain=https%3A%2F%2Fauth.pieces.services&authuser=0)
![image](https://github.com/pieces-app/support/assets/10970127/cb56723e-69c7-417e-9c1c-4e4dc14364c5)

Error Details:
```
Error 403: access_denied
Request details: response_type=code redirect_uri=https://auth.pieces.services/login/callback state=H2b_-fiYBeU2Gasqhktkc-Wv9_DArnk6 prompt=login client_id=640481513740-t4f72ofn3n7kot22mn4bor2hjs4tjv46.apps.googleusercontent.com access_type=online scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid
```

**Comment by rosie-at-pieces** [comment]
hey @truszko1 so sorry this is happening to you! this is actually a bug we've been trying to track down but are having a hard time reproducing. it would be super helpful if you could hop on a quick call with us so we can take a look!

you can book your own time with Mark using [this](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2iaRWpd1kA2k_xg2KrVi_jiTHo0POiMZSI9WAYsxs5jJ9sU2Rd2zKitLuSFd7l3FhatGzy5Vgt) link.

**Comment by truszko1** [comment]
Scheduled Tuesday 8am :)

**Comment by mark-at-pieces** [comment]
hey @truszko1 I did a little digging into this issue and is related to google social auth specifically with Auth0 ([link](https://community.auth0.com/t/access-blocked-auth0-has-not-completed-google-verification-process/124619))

I believe this to be an issue on there side and will be following this ticket up above and will update when this is resolved.

**Comment by truszko1** [comment]
okay! thanks!

**Comment by rosie-at-pieces** [comment]
@truszko1 this should be resolved now - will you please give it another shot?
