### ISSUE TITLE
Pieces os says: port already in use if i start phpstorm with pieces plugin

### ISSUE THREAD

**Issue by micksp** [pieces-app/support#534]
### Software

Pieces OS

### Operating System / Platform

Linux

### Your Pieces OS Version

11.0.0 2024-12-17

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

if i start my computer, pieces-os starts. Then, if i start phpstorm, there's a message: 
> It looks like port 5323 is occupied by another application. Pieces OS uses this port to communicate with plugins. Please, enable Pieces OS to run on port 5323.

Even if I kill the pieces-os on port 5323 and start up phpstorm, it still get's this error. So it looks like phpstorm is trying to start piecec-os again, and I think more than once.
I did snap refresh pieces-os => snap "pieces-os" has no updates available
php storm plugin is to be 10.0.0

**Comment by mack-at-pieces** [comment]
Hey @micksp - Thanks so much for the issue and so sorry for the inconvenience.

The entire Pieces for Developers Suite is actually going through an update as we speak. We are waiting for the latest JetBrains plugin to proceed through marketplace verification. This should come back online within the next 12-24 hours.

In the meantime, we'll continue to keep this original ticket up to date as things unfold https://github.com/pieces-app/support/issues/530

Thanks so much!
