### ISSUE TITLE
Pieces Desktop App - Lost Connection to PiecesOS

### ISSUE THREAD

**Issue by Sujeet76** [pieces-app/support#539]
_PiecesOS Information_

**ID:** 1e54a5eb-e233-4925-8202-979176c41cab
**User:** 406a36fe-fe49-42fe-98b3-72a6bc66058c
**Current Version:** Unknown
**Min Version Supported:** 11.0.0
**Max Version Supported:** 12.0.0
**Local Port:** 127.0.0.1:39300

_Device Information_

**Operating System:** Windows
**Current Version:** "Windows 10 Home Single Language" 10.0 (Build 26100)
**Min Version Supported:** Windows 10 Build 1903

#### When I try to add a folder to the context, PiecesOS crashes.

https://github.com/user-attachments/assets/b10af547-e88d-4694-9251-9bcad71712c7

**Comment by sirius-beck** [comment]
Same problem here, I was creating an issue now but I remembered to see if I already had one.

**Comment by mason-at-pieces** [comment]
Hey @Sujeet76 @sirius-beck, apologies for the issues here! This is a known issue and there are more details on it here: #536 

We are working on a solution at the moment. Thank you for your patience!

**Comment by sam-at-pieces** [comment]
Hey @sirius-beck , @Sujeet76 I am taking a look at a potential fix for this. If you are happy to send me your log files it would be a real help. You can find them in the pieces root directory (Documents/com.pieces.os/Support/logs and Documents/com.pieces.pfd/Support/logs). Thanks for your help!

**Comment by Sujeet76** [comment]
Hey @sirius-beck, should I send just the latest log file or all of the log files?

**Comment by sam-at-pieces** [comment]
All of the log files would be perfect, unless you remember the date you hit this issue, then just the logs from that day would be sufficient. Thanks @Sujeet76

**Comment by mark-at-pieces** [comment]
> Hey [@sirius-beck](https://github.com/sirius-beck), should I send just the latest log file or all of the log files?
the latest would be solid!

**Comment by Sujeet76** [comment]
These are the most recent log files

com.pieces.os log files
[log-12182024.zip](https://github.com/user-attachments/files/18201014/log-12182024.zip)

com.pieces.pfd log files
[log-12192024.zip](https://github.com/user-attachments/files/18201056/log-12192024.zip)

**Comment by mark-at-pieces** [comment]
I'm going to post a link to a google meet here, if you had some time to join this that would so legendary( I will stay on this call for 30-an hour)

https://meet.google.com/dbj-hrnr-zzp?authuser=0

**Comment by mark-at-pieces** [comment]
Going to close this issue for now, please refer to https://github.com/pieces-app/support/issues/536 for the continued conversation
