### ISSUE TITLE
[not critical]  Model Download Socket - Status unkown

### ISSUE THREAD

**Issue by HRA42** [pieces-app/support#55]
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

latest

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I see something strange inside the `com.pieces.pfd\production\logs` folder some strange logs when the app starts:
```
[D]  Copilot - Model Download Socket Event - Model: 415bca09-a3c4-4da8-8b99-a8d3e040c315 - {"status":"UNKNOWN"}
[D]  Copilot - Model Download Socket - Model: 415bca09-a3c4-4da8-8b99-a8d3e040c315 - Status: UNKNOWN
[D]  Copilot - Model Download Socket Event - Model: 5d4f2e60-c6a7-4888-a090-e7f8fa4e6716 - {"status":"UNKNOWN"}
[D]  Copilot - Model Download Socket - Model: 5d4f2e60-c6a7-4888-a090-e7f8fa4e6716 - Status: UNKNOWN
[D]  Copilot - Model Download Socket Event - Model: 5de13d75-592b-400c-9364-9482d334f718 - {"status":"UNKNOWN"}
[D]  Copilot - Model Download Socket - Model: 5de13d75-592b-400c-9364-9482d334f718 - Status: UNKNOWN
[D]  Copilot - Model Download Socket Event - Model: 76995ad0-bee8-4585-b4e7-0d80518c0fc1 - {"status":"UNKNOWN"}
[D]  Copilot - Model Download Socket - Model: 76995ad0-bee8-4585-b4e7-0d80518c0fc1 - Status: UNKNOWN
[D]  Copilot - Model Download Socket Event - Model: b53a84c1-3f68-4213-a2c4-c84d18153e57 - {"status":"UNKNOWN"}
[D]  Copilot - Model Download Socket - Model: b53a84c1-3f68-4213-a2c4-c84d18153e57 - Status: UNKNOWN
[D]  Copilot - Model Download Socket Event - Model: db2ccb62-0cec-4b15-9299-6a0d027ad86e - {"status":"UNKNOWN"}
[D]  Copilot - Model Download Socket - Model: db2ccb62-0cec-4b15-9299-6a0d027ad86e - Status: UNKNOWN
```

link to thread on Discord:
https://discord.com/channels/1098986658851999776/1167480766767317063/1199052222147862631

Please note, this is not critical, as no feature seems to be impaired.

**Comment by caleb-at-pieces** [comment]
@mack-at-pieces would be best to comment on this however I think this is normal logging behavior here that is expected.

Basically, each time you boot the desktop application, it will log the status of your local LLM downloads.

**Comment by mack-at-pieces** [comment]
Hi @HRA42 - Thanks for asking!

What @caleb-at-pieces mentioned is correct. We open a few web sockets when booting the Desktop App to see if any of your local LLMs are downloading or downloaded. It's possible for a local model to be downloaded via one of our plugins, so this is how the Desktop App synchronizes its state.

`status: UNKNOWN` simply means no download has been initialized or completed.
