### ISSUE TITLE
Can't connect to Pieces OS

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#56]
Original ticket: 

Failed to connect to Pieces OS

![bea9b81c3507-Pieces_OS_Launch_Failure_Error (2)](https://github.com/pieces-app/support/assets/152189388/18435828-6189-467a-b5e3-1c34c3a660eb)

Note: this issue was created automatically from an offline service ticket.

**Comment by rosie-at-pieces** [comment]
This is a known issue and we are still tracking down the root cause, so we would appreciate some assistance with this.

If you are experiencing this issue, we would love to have a short call with you to get you sorted out. Please check out Mark's [calendar](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2iaRWpd1kA2k_xg2KrVi_jiTHo0POiMZSI9WAYsxs5jJ9sU2Rd2zKitLuSFd7l3FhatGzy5Vgt) and schedule a session with him whatever time suits you.

We'll keep this ticket updated as we find the issue and roll out a fix.

**Comment by rosie-at-pieces** [comment]
We are hearing from users that restarting your computer usually solves this. Give that a try and let us know here if it doesn't work out for you!

**Comment by rosie-at-pieces** [comment]
We're trying to narrow this issue down, so if you are experiencing this issue can you please let us know if you're running M1 or Intel? Thank you!

**Comment by CBID2** [comment]
> We are hearing from users that restarting your computer usually solves this. Give that a try and let us know here if it doesn't work out for you!

Hi @rosie-at-pieces! :) I had the same problem, and restarting the app did work.

**Comment by rosie-at-pieces** [comment]
FAQ for this topic [here](https://docs.pieces.app/faq#cant-connect-to-pieces-os)!
