### ISSUE TITLE
Unable to open Pieces Copilot Service

### ISSUE THREAD

**Issue by GameTechWorld** [pieces-app/support#560]
Error: ApiException 500: Format Metrics snapshot failed.

**Installation Details**

Succeeded: true
Path: C:\Program Files\WindowsApps\com.MeshIntelligentTechnologi.PiecesOS_11.0.0.0_x64__84gz00a5z79wr/os_server.exe

**PiecesOS Information**

ID: efa70257-1d16-425e-bac3-bf0de613789e

User: 8f9629b7-bd43-4ba2-b2f6-cfecfbba744e
Current Version: 11.0.0
Min Version Supported: 11.0.0
Max Version Supported: 12.0.0
Local Port: 39300

**Device Information**

Operating System: Windows
Current Version: "Windows 10 Home Single Language" 10.0 (Build 26100)
Min Version Supported: Windows 10 Build 1903

**Comment by mark-at-pieces** [comment]
LINKED to https://github.com/pieces-app/support/issues/560, closing as a duplicate for now
