### ISSUE TITLE
Multiple well-known/health api call during reload

### ISSUE THREAD

**Issue by ahbabshahin** [pieces-app/support#569]
### Software

Web Extension

### Operating System / Platform

Windows

### Your Pieces OS Version

11.0.3

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When the pieces for developer extension are enabled, this API is called multiple times during page initialization. With every reload this happens.
http://127.0.0.1:39303/.well-known/health

**Comment by mark-at-pieces** [comment]
I believe that this is related to this issue

https://github.com/pieces-app/support/issues/562

I am going to close this as a duplicate for now.
