### ISSUE TITLE
 desktop app not installing on [macOs Sonoma 14.2.1 (23C71)], mac mini M1

### ISSUE THREAD

**Issue by karimchedid** [pieces-app/support#68]
### Software

Desktop Application

### Operating System

macOS

### Your Pieces OS Version

latest i couldn't install it 

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I am not able to install the macos package (Pieces-arm64.pkg), i tried to download it many times. I get ("The operation couldn’t be completed. (com.apple.installer.pagecontroller error -1.)", "Couldn’t open “Pieces-arm64.pkg”.")

**Comment by nathan-courtney-pieces** [comment]
Hello @karimchedid 

Please try downloading from the website again. There may have been an issue with our server. A patch was pushed today that may solve your issue.

**Comment by karimchedid** [comment]
Thanks A lot now installed and working fine
