### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Ecstasy0** [pieces-app/support#70]
### Software

Desktop Application, Pieces OS

### Operating System

macOS

### Your Pieces OS Version

Not installed

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

<img width="615" alt="Screenshot 2024-01-29 at 7 08 28 PM" src="https://github.com/pieces-app/support/assets/112030498/62abc474-93de-414c-a974-cd6024e9279b">
I am having issue while installing pieces OS on my MacBook pro 2015 intel model. Please see the above image to see the error.

**Comment by nathan-courtney-pieces** [comment]
Hello @Ecstasy0 

Please try downloading the package from our website again. There may have been an issue with our servers. A patch was pushed today that may solve your issue.
