### ISSUE TITLE
Installation Error Snapd

### ISSUE THREAD

**Issue by HenryMigo** [pieces-app/support#71]
### Software

Desktop Application, Pieces OS

### Operating System

Linux

### Your Pieces OS Version

N/A

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I am trying to install on Arch Linux either the application or pieces-os via snap but I get the error:
-----
       error: system does not fully support snapd: cannot mount squashfs image using "squashfs": 

       mount: /tmp/syscheck-mountpoint-2252065513: unknown filesystem type 'squashfs'.

       dmesg(1) may have more information after failed mount system call.
-----

**Comment by nathan-courtney-pieces** [comment]
Hello @HenryMigo 

Looks like you are having some issues with snap. 

The error suggests that you may be missing some packages, particularly **squashfs-tools**

You can try to install the package with this command: 

`sudo pacman -Sy squashfs-tools`

I would potentially restart **snapd** or your entire system after the fact and try again. 

If that doesn't solve your issue, your kernel may be outdated and you can attempt to update your system by running: 

`sudo pacman -Syu`

There may be some other things we can try, but give the above options a go first. I would also consult the Arch Linux forums to make sure you have **snapd** properly installed.

**Comment by HenryMigo** [comment]
Hi Nathan,

I will try that when I am home, I run that update almost everyday so I don't suspect it to be out of date but could definitely be missing that package!

Regards,

Henry Migo

**Comment by HenryMigo** [comment]
@nathan-courtney-pieces  That fixed the issue!
