### ISSUE TITLE
C++ snippets

### ISSUE THREAD

**Issue by Intijir** [pieces-app/support#76]
### Software

Pieces OS

### Operating System

macOS

### Your Pieces OS Version

7.3.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When using pieces and interacting with C++ comments it takes them as Java snippets.

**Comment by sam-at-pieces** [comment]
@mack-at-pieces, @rosie-at-pieces this should have been fixed in our pipelines update, we now infer the correct style for the comments.
