### ISSUE TITLE
GPT-4 does not want to make html

### ISSUE THREAD

**Issue by StioStudio** [pieces-app/support#79]
I tried a lot of different prompts but every time GPT-4 said it could not do that.

![image-7.png](https://github.com/pieces-app/support/assets/98958235/587fca7a-1c91-4770-88f6-6dfaa1a92079)

![image-8.png](https://github.com/pieces-app/support/assets/98958235/2fbc5bbb-b657-47af-8193-fe6b638bcad8)

I do believe it might be a problem directly with GPT-4, as I have heard rumours that GPT-4 is "lazy". Even though I thought this was fixed for a while a go. I don't have access to GPT-plus so I can't test this theory.

**Comment by mason-at-pieces** [comment]
Do you have anything set as context for the conversation?

Also, could you paste your exact question that you are asking to get that response?

**Comment by StioStudio** [comment]
> Do you have anything set as context for the conversation?
> 
> Also, could you paste your exact question that you are asking to get that response?

The images contains the question I asked. If it is when you say "context" you mean the files and folders added to the conversation; that would be:
* Aioewa folder (contains the extension and the website for Aioewa)
* README.md file
* manifest.json file

**Comment by StioStudio** [comment]
The repositories:
https://github.com/StioStudio/Aioewa
https://github.com/StioStudio/Aioewa-website

**Comment by mason-at-pieces** [comment]
It seems like you're adding some code to your question though since it is added that `html` code box.

Could you ensure that you're just asking "Could you create me an html page?"

**Comment by StioStudio** [comment]
Yeah, I used ctrl+shift+a on the html file

**Comment by mason-at-pieces** [comment]
Ok, that could be where you're running into some issues. I assume that HTML file is already in one of the 2 repos you added as context?

**Comment by StioStudio** [comment]
Yes, that would be: https://github.com/StioStudio/Aioewa-website/blob/main/uninstall%2Findex.html

**Comment by mason-at-pieces** [comment]
Ok, so you shouldn't have to paste it in along side your question. You should just be able to add it to the context and then ask your questions if I understand correctly.

**Comment by mason-at-pieces** [comment]
Hey @StioStudio, just bumping this post to make sure we get you the help you need. Are you still encountering the same issue?

**Comment by StioStudio** [comment]
I asked it to make a url parser in js. It answered, not totally the answer I wanted but it was an answer at least

**Comment by mason-at-pieces** [comment]
@StioStudio Well that's good to hear. If you run into a similar issue again, please open up a new issue and we will help you out 👍
