### ISSUE TITLE
download of Mistral 7b-CPU initializes, but never connects

### ISSUE THREAD

**Issue by kstingel** [pieces-app/support#84]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

7.3.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

went into ChatBot setting and attempted to acquire Mistral7B-CPU
36 hours later, the downloader still read `initialising` and shows no progress on download

by comparison, Google Chrome is able to download from https://models.mistralcdn.com/mistral-7b-v0-1/mistral-7B-v0.1.tar 
without issue - Google has acquired 4.3/13.5 Gb and is currently advising 30mins left in download

**Comment by mack-at-pieces** [comment]
Hey @kstingel ! Thanks for sharing this with us. Sorry you were running into issues with this download. Do you mind sharing the system specs of your Windows machine?

Also, there should be some log files located at the path C:\Users\user\Documents\com.pieces.pfd\production\logs - can you please share the file from the day you were experiencing this issue?

**Comment by kstingel** [comment]
Hi @mack-at-pieces I have been working in this with @jordan-pieces ...
updating Pieces OS to v8.0.0 resolved the download issue
