### ISSUE TITLE
Pieces plugin in Android Studio runs at startup anyway!

### ISSUE THREAD

**Issue by H-SamurAI** [pieces-app/support#85]
### Software

JetBrains

### Operating System

Windows

### Your Pieces OS Version

7.3.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I've disabled the plugin from opening at startup of android studio.

![image](https://github.com/pieces-app/documentation/assets/46361691/01a95ce5-0cea-40cf-994d-50b74d99ebb2)

but still opening at every time!

![image](https://github.com/pieces-app/documentation/assets/46361691/9f37dd03-bf2c-4906-ad5e-d036b48aeb98)

**Comment by kuba-pieces** [comment]
Hi @H-SamurAI, sorry to hear about your inconvenience! The setting you are referring to is not meant to disable the plugin's launch with the IDE, as this can be achieved by disabling the plugin in the plugin's section of Android Studio's settings. The setting in question is all about letting the plugin know that you don't want to launch Pieces OS, a different element of Pieces Suite, on plugin start.

 This setting was meant for our users with machines under a heavy load, so they can disable Pieces OS temporarily until they want to save something. I hope this answers your question.

The panel of which the screenshot is attached, is an onboarding panel for the plugin. We became aware of an unfortunate issue with Android Studio not supporting JCEF, a crucial IntelliJ Platform component our onboarding view relies on. We have released an updated version of the plugin working around this issue for onboarding, but a complete solution with a fresh and revamped onboarding experience is coming really soon! The good news is that the new onboarding experience is also fully functional on Android Studio regardless of the runtime supplied with it!

Let me know if you have any further questions.

**Comment by H-SamurAI** [comment]
I didn't mean to disable the plugin in the startup until i need it no! I mean it doesn't have to open this Pieces Onboarding automatically with every launch of android studio make it to be like any other plugin start with android studio just in background and when i need it i'll click it!

**Comment by kuba-pieces** [comment]
@H-SamurAI Sorry for the late reply. We have released a new version of our plugin that properly handles this view now, and it will only show this view once after you update. Please, give it a try and let us know what you think :)

**Comment by H-SamurAI** [comment]
Now it doesn't open automatically on startup. Thanks.
