### ISSUE TITLE
Pieces suddenly loses context in mid-chat, even when I've only used it's own suggested prompts in reply. Using GPT-3.5 Turbo.

### ISSUE THREAD

**Issue by ThemePark** [pieces-app/support#88]
### Software

Desktop Application

### Operating System

Windows

### Your Pieces OS Version

7.3.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I've asked Pieces to describe some of its primary uses and was getting really good responses. It indicated that I could use folders to organize my snippets (among other methods). Using only the provided prompts (since they were very relevant to me), it suddenly seemed to completely forget what we were talking about. I'm trying to make the transition from GPT-3.5 Turbo standalone to Pieces for my code development work, but this sudden loss of context has happened more than a couple of times now, and it's shaking my confidence a bit. See screenshot.
![pieces-might-have-dementia](https://github.com/pieces-app/support/assets/8115581/f89becbd-31ef-405b-869f-1459c2d7e59b)

**Comment by rosie-at-pieces** [comment]
Hi @ThemePark this is awesome feedback!

We have some work in progress that will help with the forgetting part, you should see improvements there in the next couple of releases. I'll tie one of the pull requests to this!

**Comment by rosie-at-pieces** [comment]
https://github.com/pieces-app/ml_facade/pull/230

**Comment by jimbobbennett** [comment]
Closing this as we have improved the relevancy, and recommend a later model than 3.5 Turbo
