### ISSUE TITLE
Downloading local model fails/freezes

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#89]
Original ticket: 

Downloading Mistral 7b GPU keeps failing randomly within 6% to 15% and freezes there.

Note: this issue was created automatically from an offline service ticket.

**Comment by rosie-at-pieces** [comment]
We've seen this happen with a couple of users and it was due to their internet connection each time, so if you experience this please ensure you've got a stable internet connection and give it another shot. 

Feel free to report your experience below!

**Comment by kstingel** [comment]
@rosie-at-pieces I had a similar problem with Pieces OS v7.3.1
my download attempt wasn't even connecting
I was able to fix it by updating to Pieces OS v8.0.0
