### ISSUE TITLE
Pieces OS: Installation Error on Windows

### ISSUE THREAD

**Issue by ghost** [pieces-app/support#90]
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

v7.3.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

OS: Windows 11
CPU: Ryzen 7 1700
RAM: 64 GB

After Installation with the Normal Installer (**twice**) always an Error occured that the Formats File could not be found nor it exist after checking it on the given directory "C:\Users\mxcr\Documents\com.pieces.os\production\Pieces\Formats".
![Error PNG](https://github.com/pieces-app/support/assets/121446750/c551ffcd-d252-4048-9273-c6faf3872aa9)

**Comment by ShubhamOulkar** [comment]
Need a Help.

![Screenshot 2024-02-21 095245](https://github.com/pieces-app/support/assets/91728992/7db59a98-aa49-4487-a3ac-f1eeebe9b954)

**Comment by nathan-courtney-pieces** [comment]
Does everyone here who is having this issue have Documents Library Access toggled on in their Settings > Privacy & Security > Documents ? 

<img width="768" alt="ApplicationFrameHost_WqiRTCUcwc" src="https://github.com/pieces-app/support/assets/46496645/a810daca-78b9-4b29-85b8-31f3d96bd6a0">

**Comment by ShubhamOulkar** [comment]
Yes, I have.
