### ISSUE TITLE
I am unable to use my Copilot with my id

### ISSUE THREAD

**Issue by thegautamharshit** [pieces-app/support#93]
### Software

Desktop Application, Pieces OS, JetBrains

### Operating System

Linux

### Your Pieces OS Version

7.3.1

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![help](https://github.com/pieces-app/support/assets/129443335/ae247140-8c4d-44ee-8657-52b5e39ba171)
I am unable to use my chatgpt of anyversion even though gemini is running perfeclty and this problem is only related to my primary email id which i linked to pieces because my another id which i created for testing point of view is working really fine,
please resolve this issue as soon as possible.

**Comment by rosie-at-pieces** [comment]
This was resolved - the user's personal OpenAI API key had expired. 

If you run into this issue, please either go to OpenAI and update your key OR remove the API key entirely from the Pieces desktop app and select one of the OpenAI LLMs we offer.
