### ISSUE TITLE
Pieces Copilot + Jetbrains (IntelliJ) Plugin failure

### ISSUE THREAD

**Issue by kstingel** [pieces-app/support#94]
### Software

Pieces OS, JetBrains

### Operating System

Windows

### Your Pieces OS Version

Pieces OS = 8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![image](https://github.com/pieces-app/support/assets/2832696/be3a61c1-dd70-4335-941a-b374ac8a16ac)
seeing the above message in Jetbrains IntelliJ 2023.3.4

Opened Pieces Suite to confirm my installed versions:
Pieces OS = 8.0.0
Pieces for Dev = 2.10.0
Jetbrains Plugin = 7.2.1
IntelliJ (Ult) = 2023.3.4

Tried restarting Pieces OS and IntelliJ but it didn't help

**Comment by BewaAutomatisierung-RD** [comment]
@kstingel : I guess this is a misleading error message.  Not Pieces OS needs to be updated but your Jetbrains Plugin: it should be v8.0.0.
I had the same error message but for me the Plugin was already on v8.0.0 while the Pieces OS was not available as v8 yet.  But now it is and everything seems to work.

**Comment by kstingel** [comment]
@BewaAutomatisierung-RD just tried (reinstalling) JB plugin ... 
I'm still only receiving Plugin v7.2.1

**Comment by BewaAutomatisierung-RD** [comment]
@kstingel :  I guess they called it back from the marketplace.  First they provide the JB plugin before even releasing the OS and then after releasing the OS they call back the JB plugin !?  I guess we will have to wait for an explanation by Pieces.

**Comment by rosie-at-pieces** [comment]
@kstingel @BewaAutomatisierung-RD huge apologies about this, the JetBrains review process is taking longer than expected so our versions are out of sync. We don't have control over this unfortunately so please bear with us for now. The desktop app should be working in the meantime.

Again, so sorry about the inconvience.

**Comment by rosie-at-pieces** [comment]
The JetBrains version 8.0.0 is now out and should resolve this issue, please let us know if you are still experiencing any issues!
