### ISSUE TITLE
Phi-2 GPU LLM Responses

### ISSUE THREAD

**Issue by Perspective2077** [pieces-app/support#99]
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

#08.0.0 

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

It's giving unreadable responses (look like emojis when there are not support) , repeating previous answer without even asking , nor using dedicated gpu 

![Screenshot 2024-02-21 150757](https://github.com/pieces-app/support/assets/115461545/d350fa10-0119-4d3e-9997-7c4bf96eeb7a)
![Screenshot 2024-02-21 150605](https://github.com/pieces-app/support/assets/115461545/6e9c8d71-e514-4abe-bd51-cc37f9d4dc6e)

**Comment by jimbobbennett** [comment]
@Perspective2077 - apologies for the late response. Can you try using the newer Phi-3-128K models? These weird responses can be due to exceeding the models context window size, and the newer models have a larger context. We will probably be deprecating Phi-2 soon.

**Comment by sam-at-pieces** [comment]
Closing this as it is stale and will be resolved in the next release with OLLAMA
